### ISSUE TITLE
notmuch failed to build on 10.6.8

### ISSUE THREAD

**Issue by NateEag** [Homebrew/homebrew#39945]
I've run `brew update`, but notmuch refuses to build, with ld saying:

`ld: symbol(s) not found`

while building notmuch.

Here's the gist generated by `brew gist-logs notmuch`:

https://gist.github.com/anonymous/359949fd6d3ba8e559fb

Also note that curl refused to download glib while building deps due to some SSL issue. I worked around it by wget'ing the file in question and putting it at the right spot in `brew`'s cache, but that seems like it should be fixed too.

**Comment by NateEag** [comment]
also note that `brew doctor` dislikes a number of things about my system's setup, which has evolved over many years of tinkering and installing stuff at semi-random.

I lack the expertise to recognize how likely the issues it reports are to be causing this issue.

**Comment by DomT4** [comment]
Please let us know if we can help further here, but note 10.6 support is extremely tentative at this point as very few users still use it and can assist with narrowing down the bugs on an ongoing basis.

**Comment by NateEag** [comment]
I guess I never did update this issue - I diagnosed it, and the problem turned out to be upstream:

https://notmuchmail.org/pipermail/notmuch/2015/020615.html

I submitted a patch, and was asked to make some changes for code review:

https://notmuchmail.org/pipermail/notmuch/2015/020727.html

By the time I got around to making the changes, other changes had caused further breakage on 10.6.

I recently gave up and upgraded to 10.11, where it builds just fine.

Hopefully this info helps the next intrepid 10.6er out there...

**Comment by dunn** [comment]
Thanks for the update!
