### ISSUE TITLE
curl -fsSL https://goo.gl/getgrpc | bash -s python failed to build on 10.10.5

### ISSUE THREAD

**Issue by dhruvChoudhary** [Homebrew/homebrew#49118]
curl -fsSL https://goo.gl/getgrpc | bash -s python
zlib is already installed
openssl is already installed
google-protobuf is already installed
Error: undefined method `desc' for Formulary::Formulae::Grpc:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/grpc/homebrew-grpc/Formula/grpc.rb:2:in `<class:Grpc>'
/usr/local/Library/Taps/grpc/homebrew-grpc/Formula/grpc.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by mikemcquaid** [comment]
Run `brew update`. Also, this isn't a Homebrew script so we don't support it.
