### PR TITLE
pev: add openssl dependency

### LINKED ISSUE #43936: pev failed to build on 10.11
https://gist.github.com/3fa1469b9deb807a7814

```
pehash.c:23:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[1]: *** [pehash] Error 1
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #43936

### CODE REVIEW

**Comment by DomT4** [comment]
Please bump the revisions when you add new `openssl` dependencies, if it was previously hooking the system. Thanks!

**Comment by apjanke** [comment]
Bumped revision.

**Comment by dunn** [comment]
Thanks again! Merged in 88fe21d8adbc013fc2d37214c359dd1d68b8d549 🎷🐈
