### ISSUE TITLE
racket failed to build on 10.11

### ISSUE THREAD

**Issue by amxsv** [Homebrew/homebrew#44519]
Yesterday after a clean installation of OS X 10.11 I tried to build racket and I had errors, same for plt-racket. Thanks for any help!

```
 ~$ brew install racket
==> Downloading http://mirror.racket-lang.org/installers/6.2.1/racket-minimal-6.2.1-src-builtpkgs.tgz
Already downloaded: /Library/Caches/Homebrew/racket-6.2.1.tgz
==> ./configure --enable-macprefix --prefix=/usr/local/Cellar/racket/6.2.1 --man=/usr/local/Cellar/racket/6.2.1/share/man
==> make
Last 15 lines from /Users/maksim/Library/Logs/Homebrew/racket/02.make:
  kCFCompareForcedOrdering __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) = 512 }
                                                        ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:713:115: error: expected ')'
extern const CFStringRef kCFStringTransformStripDiacritics __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) ;
                                                                                                                  ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:713:89: note: to match this '('
extern const CFStringRef kCFStringTransformStripDiacritics __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) ;
                                                                                        ^
18 errors generated.
make[4]: *** [string.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [3m] Error 2
make[1]: *** [3m] Error 2
make: *** [all] Error 2
```

https://gist.github.com/ba5952fc4f7342a9ade3

**Comment by ayberkt** [comment]
I'm having the same problem.

```
Last 15 lines from /Users/ayberkt/Library/Logs/Homebrew/racket/02.make:
  kCFCompareForcedOrdering __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) = 512 }
                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:713:115: error: expected ')'
extern const CFStringRef kCFStringTransformStripDiacritics __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) ;
                                                                                                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h:713:89: note: to match this '('
extern const CFStringRef kCFStringTransformStripDiacritics __attribute__ ((availability (macosx , introduced = 10 _5 ) ) ) ;
                                                                                        ^
18 errors generated.
make[4]: *** [string.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [3m] Error 2
make[1]: *** [3m] Error 2
make: *** [all] Error 2
```

**Comment by Blaisorblade** [comment]
I've just looked into this a bit and forwarded the issue to upstream. For now you'll need to resort to prebuilt upstream packages from http://racket-lang.org/download/.
