### ISSUE TITLE
Yap failed to build on 10.10

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#35859]
[Here are the Gists from `brew gist-logs yap`](https://gist.github.com/f76e4e69858caff41c45).

```
$ brew doctor
Your system is ready to brew.
$ brew install yap
couldn't understand kern.osversion `14.0.0'
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/yap-6.2.2.tar.gz
==> Patching
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/
==> make
gcc-4.2 -fstrict-aliasing -freorder-blocks -fsched-interblock -Wall -Wstrict-aliasing=2 -c -shared -fPIC -DBP_FREE -O3 -fomit-frame-pointer -Wall -Wstrict-prototypes -Wmissing-prototypes -g -O2 -I/usr/local/opt/gmp/include -DCUT_C=1  -DMYDDAS_MYSQL -DMYDDAS_ODBC -DCOROUTINING=1 -DRATIONAL_TREES=1 -DDEPTH_LIMIT=1 -DTHREADS=1 -D_GNU_SOURCE -DTABLING=1 -DHAVE_CONFIG_H -D_YAP_NOT_INSTALLED_=1 -I/usr/local/opt/gmp/include -I/usr/local/opt/readline/include  -I. -I./H -I./OPTYap -I./BEAM -I./MYDDAS C/gprof.c -o gprof.o
couldn't understand kern.osversion `14.0.0'
C/gprof.c: In function ‘prof_alrm’:
C/gprof.c:923: error: ‘struct __darwin_mcontext64’ has no member named ‘ss’
make: *** [gprof.o] Error 1

READ THIS: http://git.io/brew-troubleshooting
```

**Comment by mistydemeo** [comment]
Could you provide the link from `brew gist-logs yap`, please?

**Comment by bfontaine** [comment]
I did provide it in the issue:
![capture d ecran 2015-01-14 a 09 11 18](https://cloud.githubusercontent.com/assets/1334295/5735849/6d1f76ee-9bcd-11e4-8591-add3d8766a0e.png)

**Comment by mistydemeo** [comment]
Thanks - sorry, missed the link.

**Comment by jacknagel** [comment]
Can you try compiling with something other than gcc 4.2 (e.g. `brew install yap --cc=gcc-4.9`)?

**Comment by bfontaine** [comment]
@jacknagel Thanks, it works (with a warning):

```
$ brew install yap --cc=gcc-4.9
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/yap-6.2.2.tar.gz
==> Patching
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/
==> make
==> make install
Warning: yap dependency gmp was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/yap/6.2.2: 485 files, 10M, built in 3.9 minutes
```

Do you think it’s a problem on my side and/or with the formula?

**Comment by jacknagel** [comment]
I would recommend getting rid of gcc-4.2, it probably isn't worth keeping around at this point.

**Comment by bfontaine** [comment]
Yes it works when I uninstall `apple-gcc-4.2`:

```
brew install yap
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/yap-6.2.2.tar.gz
==> Patching
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/
==> make
==> make install
Warning: yap dependency gmp was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/yap/6.2.2: 485 files, 10M, built in 2.6 minutes
```

Thanks!

**Comment by lalop** [comment]
Hello,
I've the same issue installing php55.
I tried to compile with gcc4.9 but that  doesn't fix the issue for me :
```brew install php55 --cc=gcc-4.9```

When installing with this flag ENV is setted with gcc-4.9 but in the Configuration part its the 4.2 version, is it that the expected behaviour ?

```
==> /usr/local/Cellar/php55/5.5.21/bin/pear config-set php_ini /usr/local/etc/php/5.5/php.ini system
Failed to execute: /usr/local/Cellar/php55/5.5.21/bin/pear
couldn't understand kern.osversion `14.1.0'
==> Formula
Tap: homebrew/homebrew-php
Path: /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php55.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 4ca85725a146312e7e38f23f3119d90f20c7810c
Last commit: 19 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit ivybridge
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
couldn't understand kern.osversion `14.1.0'
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/sam/.rvm/rubies/ruby-1.9.3-p385/bin/ruby
Java: 1.8.0_25
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
CMAKE_PREFIX_PATH: /usr/local/opt/gettext:/usr/local/opt/icu4c:/usr/local/opt/zlib:/usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/libpng/bin:/usr/local/opt/freetype/bin:/usr/local/opt/gettext/bin:/usr/local/opt/icu4c/bin:/usr/local/opt/jpeg/bin:/usr/local/opt/unixodbc/bin:/usr/local/opt/libtool/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Thanks
Samuel

**Comment by bfontaine** [comment]
@lalop I would recommend you to open another issue for this ;)
