### ISSUE TITLE
carthage failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42378]
On OS X 10.11 Public Beta 3.

https://gist.github.com/5eab26854845c1aa00f2

Looks like it's not compatible with the current version of Swift.

```
/tmp/carthage20150801-41796-1moi3cx/Carthage/Checkouts/Box/Box/Box.swift:6:37: error: 'Printable' has been renamed to 'CustomStringConvertible'
public final class Box<T>: BoxType, Printable {
                                    ^~~~~~~~~
                                    CustomStringConvertible
/tmp/carthage20150801-41796-1moi3cx/Carthage/Checkouts/Box/Box/Box.swift:31:10: error: 'toString' has been renamed to 'String'
                return toString(value)
                       ^~~~~~~~
                       String
Swift.toString:1:48: note: 'toString' has been explicitly marked unavailable here
@available(*, unavailable) @inline(never) func toString<T>(x: T) -> String
                                               ^
```

**Comment by boek** [comment]
@apjanke I was able to get it to install by installing Xcode 6.4 and setting the Command Line Tools to that version

<img width="834" alt="screen shot 2015-08-05 at 10 51 37 am" src="https://cloud.githubusercontent.com/assets/1250545/9093267/f5644e26-3b5f-11e5-88a2-fce2b6faa21c.png">

**Comment by mikemcquaid** [comment]
@boek Unfortunately using Xcode 6.4 on OS X 10.11 will break most other things :sob:

**Comment by apjanke** [comment]
From what I've read, a given Xcode (or a given Xcode on a given OS version?) will only support the newest version of Swift at the time of its release. But newer versions of Xcode might not run on older OS versions. And Swift will intentionally have breaking non-backward-compatible changes. There's an automatic source code translator for Swift that will convert it to a newer version. But if upstream does that, then it might not run on older versions of OS X.

So... it sounds like you can't have a single Swift program source tree that can be used across several versions of OS X, without going through some contortions to build it?

Is there a way for formulae to specify that they require exact version ranges of Xcode? That could at least get a more user-friendly error for this.

I think it would be okay to run Xcode 6.4 on 10.11 as long as it's not your default Xcode, and you don't have its CLT installed. (E.g. if you installed it as `/Applications/Xcode-6.4.app` instead.) Don't think there's currently a way for Homebrew to make use of it though, is there?

**Comment by DomT4** [comment]
Moving to tracking in #40837. If you report this one upstream let us know in that thread and I'll add a link to that report, Thanks!

Echoing Mike's comment above, whilst 6.x Xcode may fix the Swift issue, expect it to break a *lot* of other stuff. Homebrew will follow whatever Xcode you've set with `xcode-select`, but if stuff breaks and you've still got 6.4 as the default, please switch back to 7.0 & double check before reporting it.
