### PR TITLE
yap: don't use GCC 5, which breaks

### LINKED ISSUE #41558: Yap failed to build on 10.10
This is a follow-up to #35936. I don’t know if this is related to #35859.

```
$ brew install yap
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/yap-6.2.2.tar.gz
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/
==> make
      _p_trie_usage in tries.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [tries.dylib] Error 1
make: *** [all] Error 2
```

==> [gist logs](https://gist.github.com/67cf3182037fb9e26088) <==

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #41558

### CODE REVIEW

**Comment by mistydemeo** [comment]
Looks like this doesn't build with certain other GCCs, either. I'm testing to see what it does build with.

**Comment by apjanke** [comment]
GCC 4.9 is the only one I can report "Yes" on, though their mailing list seems to indicate 4.2 should work, too.

**Comment by mistydemeo** [comment]
What version of OS X are you on? I can't get it to work with 4.2, 4.8 or 4.9 on 10.11.

**Comment by apjanke** [comment]
10.9.5. I've also got a 10.11 machine; pulling that out to test too...

**Comment by apjanke** [comment]
I was using the system GCC 4.9 on 10.9, not the homebrew-versions `gcc49`. Would that make a difference to things?

**Comment by mistydemeo** [comment]
Xcode doesn't include GCC 4.9 - Apple never shipped a version past 4.2. Xcode 6.2 (which is probably what you have?) doesn't actually include any GCC at all, only clang. We've got a version table [in the docs](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Xcode.md) for reference.

**Comment by apjanke** [comment]
Oops! My mistake; it was the Homebrewed `gcc49` formula. I didn't recall ever installing it on this machine. I have Xcode 5.0.2 and 6.2 on that box.

Worked for me on 10.11.1 with `gcc49`. [Here are logs from the build.](https://gist.github.com/apjanke/1e2fa513410294246914)

**Comment by apjanke** [comment]
Should we mark some additional GCCs as not working?

**Comment by mikemcquaid** [comment]
> Should we mark some additional GCCs as not working?

:+1:, good idea.

**Comment by DomT4** [comment]
What's the status here? Almost submitted a fresh PR before stumbled across it :blush:.

**Comment by mikemcquaid** [comment]
:+1: to just merging this for now and iterating

**Comment by DomT4** [comment]
May be worth rebasing on master. I added a `bottle :disable` line the other night to workaround an issue whilst I looked into it. As it turned out, the issue had been fixed by this PR :smile:.

Still won't be able to pull bottles, but can at least update the disable reasoning.

**Comment by apjanke** [comment]
Rebased on master, leaving the `bottle :disable` in and updating the comment. Look right?

**Comment by DomT4** [comment]
LGTM :smiley:
