### PR TITLE
bazel 0.1.4

### PR DESCRIPTION
**Pull request by martinwicke**

### CODE REVIEW

**Comment by DomT4** [comment]
Failed to build on OS X 10.9:

```
🍃  Building Bazel from scratch...........
Compiling xcode-locator...
/usr/bin/xcrun clang -fobjc-arc -framework CoreServices -framework Foundation -o /var/folders/_z/11_kwl954xvch_n92gnzdjzw0000gp/T/bazel.XiHLk8ct/xcode-locator src/main/tools/xcode_locator.m
src/main/tools/xcode_locator.m:114:40: warning: implicit declaration of function 'LSCopyApplicationURLsForBundleIdentifier' is invalid in C99 [-Wimplicit-function-declaration]
    NSArray *array = CFBridgingRelease(LSCopyApplicationURLsForBundleIdentifier(
                                       ^
src/main/tools/xcode_locator.m:114:40: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'CFTypeRef' (aka 'const void *') [-Wint-conversion]
    NSArray *array = CFBridgingRelease(LSCopyApplicationURLsForBundleIdentifier(
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:107:54: note: passing argument to parameter 'X' here
NS_INLINE id CFBridgingRelease(CFTypeRef CF_CONSUMED X) {
                                                     ^
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_LSCopyApplicationURLsForBundleIdentifier", referenced from:
      _main in xcode_locator-f9a5ad.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by damienmg** [comment]
@c-parsons: What's happening there?

**Comment by damienmg** [comment]
(btw: thanks Martin for doing that, it totally fell off my radar)

**Comment by damienmg** [comment]
Oh wait I just saw "10.9": I think it is ok to remove the support for mavericks.

**Comment by DomT4** [comment]
If upstream are happy that's intentional we can pass:
```ruby
depends_on :macos => :yosemite
```
In the formula.

**Comment by damienmg** [comment]
From the Bazel side it's ok, we don't have the mean to test all OS X version.
