### ISSUE TITLE
vault failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44035]
https://gist.github.com/26ecc9f2763f18f76d54

```
go generate ./...
==> Getting dependencies...
# github.com/hashicorp/vault/physical
physical/s3.go:59: undefined: credentials.EC2RoleProvider
physical/s3.go:64: cannot use region (type string) as type *string in field value
```

**Comment by apjanke** [comment]
Same error for me on OS X 10.9.5 with Xcode 6.2. Not 10.11-specific.
