### ISSUE TITLE
exact-image failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42485]
https://gist.github.com/2f292334b3db60de7d12

On OS X 10.11 PB4, no CLT.

Failing with some undefined functions.

```
codecs/gif.cc:65:7: error: use of undeclared identifier 'PrintGifError'
      PrintGifError();
      ^
```

**Comment by mistydemeo** [comment]
I can repro building on 10.10; doesn't seem to be 10.11 specific.

**Comment by mistydemeo** [comment]
It looks like this has broken with recent GIFLIB. When building from source, it's opportunistically picking up a GIFLIB you already have installed; the bottled version works since the bot doesn't have GIFLIB.

r2084 in the exact-image svn repo contains fixes for recent GIFLIB, but they're designed for GIFLIB 5 and aren't compatible with the one Homebrew uses.

**Comment by mistydemeo** [comment]
Should be fixed, can you `brew update` and retry?

**Comment by apjanke** [comment]
Yep. Succeeded on 10.11 after a `brew update`.
