### ISSUE TITLE
ffmpegthumbnailer 2.1.1 fails to build on 10.8

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew#49293]
Build fails on line 15 of make:

```
/usr/local/Library/ENV/4.3/clang++   -D__STDC_CONSTANT_MACROS -Dlibffmpegthumbnailer_EXPORTS -I/tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1 -I/usr/local/include  -std=c++11 -DNDEBUG -fPIC   -o CMakeFiles/libffmpegthumbnailer.dir/libffmpegthumbnailer/moviedecoder.cpp.o -c /tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.cpp
In file included from /tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.cpp:17:
/tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.h:20:10: fatal error: 'cinttypes' file not found
#include <cinttypes>
         ^
1 error generated.
```

Output of `brew gist-logs ffmpegthumbnailer`:
https://gist.github.com/anonymous/388f608ab513d6a4e296

**Comment by ilovezfs** [comment]
@dcwar This fixes it:

```
diff --git a/Library/Formula/ffmpegthumbnailer.rb b/Library/Formula/ffmpegthumbnailer.rb
index 06503da..d8c2403 100644
--- a/Library/Formula/ffmpegthumbnailer.rb
+++ b/Library/Formula/ffmpegthumbnailer.rb
@@ -1,8 +1,9 @@
 class Ffmpegthumbnailer < Formula
   desc "Create thumbnails for your video files"
   homepage "https://github.com/dirkvdb/ffmpegthumbnailer"
-  url "https://github.com/dirkvdb/ffmpegthumbnailer/archive/2.1.1.tar.gz"
-  sha256 "e43d8aae7e80771dc700b3d960a0717d5d28156684a8ddc485572cbcbc4365e9"
+  url "https://github.com/dirkvdb/ffmpegthumbnailer/releases/download/2.1.1/ffmpegthumbnailer-2.1.1.tar.bz2"
+  sha256 "f1f1b54b7903d726a118d7b2a2992cacef561517567f3a547964ad48cb5c89bd"
+  head "https://github.com/dirkvdb/ffmpegthumbnailer.git"
 
   bottle do
     cellar :any
@@ -18,7 +19,13 @@ class Ffmpegthumbnailer < Formula
   depends_on "ffmpeg"
 
   def install
-    system "cmake", *std_cmake_args
+    ENV.cxx11 if MacOS.version < :mavericks
+
+    args = std_cmake_args
+    args << "-DENABLE_GIO=ON"
+    args << "-DENABLE_THUMBNAILER=ON"
+
+    system "cmake", *args
     system "make"
     system "make", "install"
   end
```

**Comment by ilovezfs** [comment]
@DomT4 This fixes the regression introduced by https://github.com/Homebrew/homebrew/pull/49267
