### PR TITLE
voms: add openssl dependency

### LINKED ISSUE #44040: voms failed to build on 10.11
https://gist.github.com/0396db578aed71b62d5c

Can't find OpenSSL.

```
In file included from sslutils.c:36:
../../src/include/myproxycertinfo.h:29:10: fatal error: 'openssl/x509.h' file not found
#include <openssl/x509.h>
         ^
1 error generated.
make[2]: *** [libssl_utils_nog_la-sslutils.lo] Error 1
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #44040
Fixes build failure on 10.11

### CODE REVIEW

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/ac98fac723eb3798a8a94e4b616afa1e06c59bb5. Thank you @apjanke!
