### ISSUE TITLE
tpp tpp/1.3.1/libexec/ncurses-ruby/ncurses_bin.bundle: [BUG] Segmentation fault at 0x00000000000418

### ISSUE THREAD

**Issue by lloydde** [Homebrew/homebrew#38378]
$ tpp simple.tpp 
/usr/local/Cellar/tpp/1.3.1/libexec/ncurses-ruby/ncurses_bin.bundle: [BUG] Segmentation fault at 0x00000000000418
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

where simple.tpp is the sample at http://www.ngolde.de/tpp.html

$ brew gist-logs tpp
https://gist.github.com/anonymous/30769e9a11805ffdb9ac

~~~
-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0006 p:-17579773141246 s:0030 e:000029 TOP    [FINISH]
c:0005 p:---- s:0028 e:000027 CFUNC  :require
c:0004 p:0113 s:0024 e:000023 METHOD /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54
c:0003 p:0022 s:0014 e:000013 METHOD /usr/local/bin/tpp:10
c:0002 p:0288 s:0011 E:002538 EVAL   /usr/local/bin/tpp:1743 [FINISH]
c:0001 p:0000 s:0002 E:0009f0 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/bin/tpp:1743:in `<main>'
/usr/local/bin/tpp:10:in `load_ncurses'
/Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

-- Machine register context ------------------------------------------------
 rax: 0x0000000000000030 rbx: 0x000000010d885291 rcx: 0x0000000000000000
 rdx: 0xfffffffffffffff0 rdi: 0x0000000000000030 rsi: 0x0000000000000000
 rbp: 0x00007fff52e77e70 rsp: 0x00007fff52e77e70  r8: 0x000000000000000b
  r9: 0x00000000fffffff8 r10: 0x0000000000000a58 r11: 0x00007fff875a8c40
 r12: 0x00007fff72fa0070 r13: 0x00007fe8e0408fd0 r14: 0x0000000000000007
 r15: 0x00007fff52e77f30 rip: 0x000000010d8e249f rfl: 0x0000000000010246

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010d03f98b rb_vm_bugreport + 155
1   ruby                                0x000000010cee3e80 rb_bug_context + 480
2   ruby                                0x000000010cfbc2f3 sigsegv + 83
3   libsystem_platform.dylib            0x00007fff875a7f1a _sigtramp + 26
4   libruby.2.0.0.dylib                 0x000000010d8e249f ruby_xmalloc + 17
5   ???                                 0x00007fff52e77e90 0x0 + 140734584290960

-- Other runtime information -----------------------------------------------

* Loaded script: /usr/local/bin/tpp

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 encdb.so
    4 trans/transdb.so
    5 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/unicode_normalize.rb
    6 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/x86_64-darwin14/rbconfig.rb
    7 thread.rb
    8 thread.so
    9 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/compatibility.rb
   10 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/defaults.rb
   11 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/deprecate.rb
   12 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/errors.rb
   13 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/version.rb
   14 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb
   15 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/platform.rb
   16 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb
   17 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb
   18 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/util/stringio.rb
   19 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb
   20 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/exceptions.rb
   21 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb
   23 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /Users/ll/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
Don't forget to include the above Crash Report log file.
For details: http://www.ruby-lang.org/bugreport.html

Abort trap: 6
~~~

Crash report from /Users/ll/Library/Logs/DiagnosticReports
https://gist.github.com/c4ba2d39610bce494c05

**Comment by tdsmith** [comment]
I bet the problem is that `libexec/ncurses-ruby/ncurses_bin.bundle` is linked to system Ruby:

```
darkside:ncurses-ruby tim$ otool -L ncurses_bin.bundle 
ncurses_bin.bundle:
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib (compatibility version 2.0.0, current version 2.0.0)
    (other stuff)
```

You may be able to get around this by rebuilding with `--env=std` but I wonder if there's a better fix, like using `-undefined dynamic_lookup` instead of linking to libruby (which is the "right" fix when Python stuff does this). In Pythonland we're reasonably confident that system Python is ABI-compatible with the Python the user will actually use, which is probably not true for Rubies?

**Comment by lloydde** [comment]
@tdsmith thanks for the suggestion to try `--env=std`. That does change the symptom, but it still 

~~~
dyld: lazy symbol binding failed: Symbol not found: _STR2CSTR
                                                               Referenced from: /usr/local/Cellar/tpp/1.3.1/libexec/ncurses-ruby/ncurses_bin.bundle
                                                Expected in: flat namespace

                                                                           dyld: Symbol not found: _STR2CSTR
         Referenced from: /usr/local/Cellar/tpp/1.3.1/libexec/ncurses-ruby/ncurses_bin.bundle
                                                                                               Expected in: flat namespace

                     Trace/BPT trap: 5
~~~

which looks like it might relate to some of the compiler warnings, shown in https://gist.github.com/anonymous/30769e9a11805ffdb9ac .

I googled and found complaints against ruby 1.9.2 and the mention that ffi-ncurses might provide some relief. Ruby land is foreign to me, so I instead I've tried:

~~~bash
$ rvm use 1.8.7
Using /Users/ll/.rvm/gems/ruby-1.8.7-head
$ brew install --env=std tpp
~~~

tpp now appears to be working, though tpp is also completely new to me.

I'll update issue description with the workaround. Thanks again @tdsmith .
/fyi @habibalamin : who wrote the recipe.

**Comment by habibalamin** [comment]
Had this tab open for the past 6 days (damn, didn't realise it's been that long), just wondering how to respond. I'm sorry, but this seems a little over my head. I was able to reproduce it, though, FWIW (OS X 10.9.5 Build 13F34, MacBookAir6,2).

**Comment by habibalamin** [comment]
Just found the following link, which may be helpful, since it seems to be fixed by downgrading to Ruby 1.9:

<blockquote>We believe that the bug you reported is fixed in the latest version of
tpp, which is due to be installed in the Debian FTP archive.</blockquote>
— [#671530 - tpp: does not work with ruby 1.9 - Debian Bug report logs](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=671530)

This can probably be fixed by updating the URL in the formula to point to the latest version, then.

**Comment by habibalamin** [comment]
Huh, looks like we're already on the latest version, but Debian has some unofficial patches? Not sure what's going on there.

**Comment by habibalamin** [comment]
Looks like you can download the patch from [here](https://tracker.debian.org/pkg/tpp) if you click on one of the versions. Or just click [here](http://ftp.de.debian.org/debian/pool/main/t/tpp/tpp_1.3.1-2.diff.gz) for the 1.3.1 patch 2 diff file from Debian. Looking through it doesn't reveal anything that should fix it for Ruby 1.9, though.

**Comment by habibalamin** [comment]
[This](http://launchpadlibrarian.net/175185676/tpp_1.3.1-3build1_1.3.1-4.diff.gz) looks promising, though. It's a diff file from Ubuntu, search for "1.9".

**Comment by lloydde** [comment]
Good digging @habibalamin ! For me, I'm good for now with the workaround.

**Comment by habibalamin** [comment]
Seems like the commits have already been applied to the main repository, but have not been tagged for release.

**Comment by habibalamin** [comment]
Nope, still segfaults. Sorry!
