### PR TITLE
uwsgi 2.0.11.2, openssl linkage fix

### LINKED ISSUE #44018: uwsgi failed to build on 10.11
https://gist.github.com/958d206bd0c643dbf8fe

```

python
uwsgiconfig.py
--build
brew

core/socket.c:713:28: error: use of undeclared identifier 'SOL_TCP'
                if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                                         ^
1 error generated.

```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #44018

Supplies extra CFLAGS/LDFLAGS to get it to actually use the brewed openssl instead of the system one.

### CODE REVIEW

**Comment by xu-cheng** [comment]
Thanks for the pull request! 🎉 Homebrew depends on contributions from community members like you and we're grateful for your support.
