### PR TITLE
bokken: fix build on Yosemite

### LINKED ISSUE #32016: bokken failed to build on OSX 10.10 due to Python 2.5 dependency
I know 10.10 is not supported as it is not released yet but I believe the problem is not 10.10 specific.

When trying to brew bokken it fails at `make` step with the following error:

    In file included from ../../src/pydistorm.c:15:
    ../../src/pydistorm.h:25:11: fatal error: 'python2.5/Python.h' file not found
     #include <python2.5/Python.h>    
              ^
    1 error generated.

See [Gist](https://gist.github.com/mgttlinger/9876d7fd0a4204a2e268) for outputs.

### PR DESCRIPTION
**Pull request by tdsmith**
Convinces distorm64 to look for modern Python headers; fixes binding installation locations for radare2.

Closes #32016.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Worth submitting an upstream patch for this (if we haven't already)?

**Comment by tdsmith** [comment]
The radare makefile issue should be reported; it's a bug that we have to spec those. On further reading, distorm3 is the successor project to distorm64 and seems to be supported by pyew so maybe it's worth switching.

**Comment by tdsmith** [comment]
radare2 0.9.8 is out and should be included here

**Comment by peasead** [comment]
I know that this has been discussed a few times, but I'm not sure what needs to be done.

I've run 'brew update' but that hasn't resolved the issue. I've also tried 'git pull' in /usr/local/bin for 'brew' but also no luck.

**Comment by tdsmith** [comment]
It needs to be fixed.

**Comment by Jo-Con-El** [comment]
Actually even Bokken 1.7 has been released a few days ago...

**Comment by bfontaine** [comment]
Any update on that?

**Comment by xenio** [comment]
This workaround fix the problem with Python but I still cant' install on Yosemite.
http://securityinone.com/tutorial-how-to-install-bokken-on-mac-os-x-10-10/

**Comment by kenji21** [comment]
Install succeed for me using this patch. But running bokken don't start very well :

```
Starting bokken, running on:
  Python version:
    2.7.9 (default, Jan  7 2015, 11:49:12)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
  GTK version: 2.24.25
  PyGTK version: 2.24.0

Traceback (most recent call last):
  File "/usr/local/Cellar/bokken/1.6/libexec/bokken/bokken.py", line 35, in <module>
    main.main('', '')
  File "/usr/local/Cellar/bokken/1.6/libexec/bokken/ui/main.py", line 411, in main
    MainApp(target, backend)
  File "/usr/local/Cellar/bokken/1.6/libexec/bokken/ui/main.py", line 77, in __init__
    dialog = file_dialog.FileDialog(dependency_check.HAS_PYEW, dependency_check.HAS_RADARE, self.backend, self.target, True)
  File "/usr/local/Cellar/bokken/1.6/libexec/bokken/ui/file_dialog.py", line 41, in __init__
    self.set_icon_from_file(os.path.dirname(__file__)+os.sep+'data'+os.sep+'bokken.svg')
glib.GError: Impossible de reconnaître le format d'image du fichier « /usr/local/Cellar/bokken/1.6/libexec/bokken/ui/data/bokken.svg »
```

**Comment by kenji21** [comment]
```brew install librsvg```

fixed it

**Comment by smarek** [comment]
This is indeed valid fix, however `radare2` formula looks different currently.
Also fixes to `radare2` library will resolve the issue https://github.com/inguma/bokken/issues/18

**Comment by bfontaine** [comment]
This PR needs to be rebased on top of `master`.

**Comment by DomT4** [comment]
Presuming dead, but feel free to reopen otherwise Tim!
