### ISSUE TITLE
PHP56 failed to build on 10.10.2

### ISSUE THREAD

**Issue by pdechanoz** [Homebrew/homebrew#38045]
Upgrading php56 
./configure --prefix=/usr/local/Cellar/php56/5.6.7 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/5.6 --with-config-file-path=/usr
==> make
      _zif_pg_lo_truncate in pgsql.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1
make: *** Waiting for unfinished jobs....

https://gist.github.com/626bd9cf19d107ffe481

**Comment by mistydemeo** [comment]
Please report this to [homebrew-php](https://github.com/josegonzalez/homebrew-php) - thanks!

**Comment by mikemcquaid** [comment]
@mistydemeo Let's move issues with https://github-issue-mover.appspot.com

**Comment by mikemcquaid** [comment]
This issue was moved to Homebrew/homebrew-php#1632
