### ISSUE TITLE
gpsim failed to build on 10.10.3

### ISSUE THREAD

**Issue by mogen317** [Homebrew/homebrew#38503]
gpsim failed to build with error:
```
==> make all
mv -f .deps/gpsim_modules.Tpo .deps/gpsim_modules.Plo
mv -f .deps/resistor.Tpo .deps/resistor.Plo
mv -f .deps/usart.Tpo .deps/usart.Plo
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Link to Gist: [https://gist.github.com/076fb252771e99fbbea3](https://gist.github.com/076fb252771e99fbbea3)

**Comment by tdsmith** [comment]
Error is
```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I.. -I/usr/local/Cellar/glib/2.44.0/include/glib-2.0 -I/usr/local/Cellar/glib/2.44.0/lib/glib-2.0/include -I/usr/local/opt/gettext/include -g -O2 -MT switch.lo -MD -MP -MF .deps/switch.Tpo -c switch.cc -o switch.o
switch.cc:585:30: error: addition of default argument on redeclaration makes this constructor a default constructor
  Switch::Switch(const char *_new_name=0)
                             ^         ~
./switch.h:91:5: note: previous declaration is here
    Switch(const char *_name);
    ^
1 error generated.
make[2]: *** [switch.lo] Error 1
```

OS X: 10.10.3-x86_64
Xcode: 6.3
CLT: 6.3.0.0.1.1428348375

**Comment by jacknagel** [comment]
Is this an upstream issue caused by stricter compilation?
