### ISSUE TITLE
libtomcrypt failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43906]
https://gist.github.com/5e9b2308816dd4e01b73

Same failure on 10.10. Works on 10.9.

Upstream issue: same build error happens when building outside Homebrew. Upstream issue: libtom/libtomcrypt#82.

**Comment by mikemcquaid** [comment]
It's been broken for 2 major OS X releases so: boneyard time.

**Comment by apjanke** [comment]
Doesn't build on last two OS X releases; current 1.17 release is from 2010; upstream bug open for five months. Yeah, boneyard time.

**Comment by kimsama** [comment]
Got the following error on OSX 10.11.4 when it installs 'libtomcrypt'.

```
==> make library
Last 15 lines from /Users/kims/Library/Logs/Homebrew/libtomcrypt/01.make:
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:277:24: error: constraint 'I' expects an integer constant expression
      :"0" (word),"I" (i));
                       ^
./src/headers/tomcrypt_macros.h:368:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
./src/headers/tomcrypt_macros.h:376:24: error: constraint 'J' expects an integer constant expression
      :"0" (word),"J" (i));
                       ^
4 errors generated.
make: *** [src/ciphers/aes/aes.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/ciphers/aes/aes_enc.o] Error 1

READ THIS: https://git.io/brew-troubleshooting
libtomcrypt was moved to homebrew-boneyard because it has unfixable issues.
Please do not file any issues about this. Sorry!
```

**Comment by mikemcquaid** [comment]
> libtomcrypt was moved to homebrew-boneyard because it has unfixable issues.
> Please do not file any issues about this. Sorry!

@kimsama We don't support `libtomcrypt` any more, sorry.

**Comment by kimsama** [comment]
ok, thanks, anyway. :-)
