### ISSUE TITLE
gtmess failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42503]
https://gist.github.com/0aeeacb833dbe81222f5

On OS X 10.11 PB4, no CLT.

```
pass.c:42:9: fatal error: 'openssl/ssl.h' file not found
#include<openssl/ssl.h>
        ^
1 error generated.
make[2]: *** [pass.o] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```
