### PR TITLE
ffmpegthumbnailer: Fix build on mountain lion

### LINKED ISSUE #49293: ffmpegthumbnailer 2.1.1 fails to build on 10.8
Build fails on line 15 of make:

```
/usr/local/Library/ENV/4.3/clang++   -D__STDC_CONSTANT_MACROS -Dlibffmpegthumbnailer_EXPORTS -I/tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1 -I/usr/local/include  -std=c++11 -DNDEBUG -fPIC   -o CMakeFiles/libffmpegthumbnailer.dir/libffmpegthumbnailer/moviedecoder.cpp.o -c /tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.cpp
In file included from /tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.cpp:17:
/tmp/ffmpegthumbnailer20160218-48533-1knymgy/ffmpegthumbnailer-2.1.1/libffmpegthumbnailer/moviedecoder.h:20:10: fatal error: 'cinttypes' file not found
#include <cinttypes>
         ^
1 error generated.
```

Output of `brew gist-logs ffmpegthumbnailer`:
https://gist.github.com/anonymous/388f608ab513d6a4e296

### PR DESCRIPTION
**Pull request by ilovezfs**
This also uses the args the INSTALL file says to use, adds the head url,
and uses the release tarball instead of the source tarball.

Closes #49293

### CODE REVIEW

**Comment by ilovezfs** [comment]
@DomT4 This fixes the regression introduced by #49267

**Comment by mikemcquaid** [comment]
Thanks again @ilovezfs!

**Comment by ilovezfs** [comment]
@mikemcquaid You're welcome. Did this need a revision bump, too, for the formula or bottle block?

**Comment by mikemcquaid** [comment]
@ilovezfs I think a bottle bump is probably enough given it doesn't affect all platforms. Bottle bumps are handled automatically.
