### ISSUE TITLE
mongrel2 failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43925]
https://gist.github.com/d6bca35c2dee11e04b8c

```
In file included from src/mem/halloc.c:23:
src/mem/align.h:33:25: error: typedef redefinition with different types ('union max_align' vs 'long double')
typedef union max_align max_align_t;
                        ^
/Applications/Xcode-7-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/__stddef_max_align_t.h:32:21: note: previous definition is here
typedef long double max_align_t;
                    ^
1 error generated.
```

That's a little odd; from Googling, `max_align_t` is a standard C++ type. Build succeeds under 10.9 for me. Maybe it's an incompatibility with Xcode 7?

**Comment by apjanke** [comment]
Reported issue upstream: https://github.com/mongrel2/mongrel2/issues/279
