### PR TITLE
whereami: boneyard

### LINKED ISSUE #44044: whereami failed to build on 10.11
https://gist.github.com/7d7da4f9f9a4ad0d3db3

Swift compilation failure of some sort. May be a Swift version compatibility issue with the update in Xcode 7.

```
[...snip...]
/tmp/whereami20150916-39009-ycsmz1/whereami-1.0/whereami/SwiftCLI/SignatureParser.swift:120:71: error: 'utf16Count' is unavailable: Take the count of a UTF-16 view instead, i.e. str.utf16.count
        return arg.substringWithRange(NSMakeRange(1 * multiplier, key.utf16Count - 2 * multiplier))
                                                                      ^~~~~~~~~~
Foundation.String:224:7: note: 'utf16Count' has been explicitly marked unavailable here
  var utf16Count: Int { get }
      ^

** INSTALL FAILED **
```

### PR DESCRIPTION
**Pull request by DomT4**
Have given this one a *long* time of being broken with no new release, despite one requested upstream. Treating the project as dead. Feel free to unboneyard if a new release becomes available that works.

Closes #44044.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by rafaelrinaldi** [comment]
RIP

**Comment by DomT4** [comment]
If you can get upstream to update this to use a compatible Swift and tag a new release we could look at re-inclusion but the project seems unmaintained at the moment.

**Comment by rafaelrinaldi** [comment]
FYI I've made a CLI with the same name that does exactly the same thing: https://github.com/rafaelrinaldi/whereami
