### PR TITLE
bulk_extractor: add openssl dependency

### LINKED ISSUE #43912: bulk_extractor failed to build on 10.11
https://gist.github.com/56a26032bc6ccdc10d57

Can't find OpenSSL.

```
In file included from ../src/be13_api/feature_recorder.h:60:
./dfxml/src/hash_t.h:60:2: error: OpenSSL required for hash_t.h
#error OpenSSL required for hash_t.h
 ^
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #43912
Also switches to `assert_match` in test to satisfy `brew audit`.

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/0c7cfea5c54d1ffd872c2cf36b1b48b1707e9719. Thank you again!
