### ISSUE TITLE
irods failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42675]
https://gist.github.com/89c054b634d5435ccb17

Fails to locate OpenSSL.

```
Compile core base64.o...
In file included from /private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/src/base64.c:5:
In file included from /private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/include/rodsClient.h:12:
In file included from /private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/include/rods.h:19:
In file included from /private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/include/sockComm.h:10:
/private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/include/rcConnect.h:31:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[1]: *** [/private/tmp/irods20150803-66333-b0lz7o/irods-legacy-3.3.1/iRODS/lib/core/obj/base64.o] Error 1
make: *** [libs] Error 2
```
