### ISSUE TITLE
bokken failed to build on OSX 10.10 due to Python 2.5 dependency

### ISSUE THREAD

**Issue by mgttlinger** [Homebrew/homebrew#32016]
I know 10.10 is not supported as it is not released yet but I believe the problem is not 10.10 specific.

When trying to brew bokken it fails at `make` step with the following error:

    In file included from ../../src/pydistorm.c:15:
    ../../src/pydistorm.h:25:11: fatal error: 'python2.5/Python.h' file not found
     #include <python2.5/Python.h>    
              ^
    1 error generated.

See [Gist](https://gist.github.com/mgttlinger/9876d7fd0a4204a2e268) for outputs.

**Comment by Jo-Con-El** [comment]
I know that it's silly, but have you tried to replace that header with a more advanced one?  10.10 shipped 2.6 and 2.7 headers.

**Comment by tdsmith** [comment]
Yeah, looks like Debian applies a small patch to distorm64; we can probably just inreplace this away. https://sources.debian.net/src/distorm64/1.7.30-1/debian/patches/101_python_path/

**Comment by Jo-Con-El** [comment]
Oh, look, this is me! :-)  I didn't even remember that I made that patch.

**Comment by JanSimek** [comment]
I still have this issue when installing Bokken through Homebrew.

```
Already downloaded: /Library/Caches/Homebrew/bokken--distorm64-1.7.30.tar.gz
==> make
 #include <python2.5/Python.h>
          ^
1 error generated.
make: *** [../../src/pydistorm.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tdsmith** [comment]
Oops, closed my PR against bokken accidentally. It needs work and I don't use it so it's not a real priority for me; you can use #36052 as a starting point if you want to take a crack at it.

**Comment by Jo-Con-El** [comment]
Anyway we are going to deprecate the pyew engine (which is the culprit of using distorm64) in the next release (1.7 is out since a couple of days), so maybe you can move on and just prefer radare2-only builds.

**Comment by Wingless-Archangel** [comment]
After I try to install again the same error is still persist in homebrew. 
```
brew install bokken
==> Downloading https://inguma.eu/attachments/download/197/bokken-1.6.tar.gz
Already downloaded: /Library/Caches/Homebrew/bokken-1.6.tar.gz
==> Downloading http://ftp.de.debian.org/debian/pool/main/d/distorm64/distorm64_
Already downloaded: /Library/Caches/Homebrew/bokken--distorm64-1.7.30.tar.gz
==> make
 #include <python2.5/Python.h>
          ^
1 error generated.
make: *** [../../src/pydistorm.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
bokken: fix build on Yosemite https://github.com/Homebrew/homebrew/pull/36052
bokken failed to build on OSX 10.10 due to Python 2.5 dependency https://github.com/Homebrew/homebrew/issues/32016
```

What should I do to fix this issue? Should I comment to install distorm64 and pyew in the formula?

**Comment by smarek** [comment]
I can confirm this issue exists on 10.10, and PR #36052 when merged fixes the issue

**Comment by apjanke** [comment]
Same failure on 10.11 beta, too.

https://gist.github.com/apjanke/4a7d412815ab5f3d7269

**Comment by DomT4** [comment]
This was fixed.
