### ISSUE TITLE
ansible 1.9.3 fails to build on Xcode-only OS X 10.11

### ISSUE THREAD

**Issue by renaudguerin** [Homebrew/homebrew#43661]
Hi,

ansible 1.9.2 was building fine, trying to upgrade to 1.9.3 and the following happens :

```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/ansible/1.9.3/libexec/vendor --single-version-externally-managed --record=installed.txt
c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

Full gist : https://gist.github.com/anonymous/598cad13d3a36f3e9753

**Comment by lucas-clemente** [comment]
I have the same issue, here's my gist: https://gist.github.com/anonymous/a62346c61f82f1a0c310

**Comment by tdsmith** [comment]
Installing the Xcode Command Line Tools package with `xcode-select --install` is probably a workaround.

**Comment by renaudguerin** [comment]
Confirmed that it works by updating the CLT package

**Comment by DomT4** [comment]
Installing the CLT is the recommended workaround for now if anyone else stumbles onto this. Closing here, since the `ffi.h` not found issue is known and not exclusive to `ansible`.
