### ISSUE TITLE
rcs failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43996]
https://gist.github.com/50b61f779485414217e7

```
/Library/Developer/CommandLineTools/usr/bin/make  install-am
clang -DHAVE_CONFIG_H -I. -I../lib  -I'../lib'   -g -O2 -c -o b-anchor.o b-anchor.c
In file included from b-anchor.c:21:
./base.h:758:3: error: '_Noreturn' keyword must precede function declarator
  exiting;
  ^~~~~~~
./base.h:44:18: note: expanded from macro 'exiting'
#define exiting  _Noreturn
                 ^
```

Sounds similar to the fibjs error.

**Comment by aufflick** [comment]
It's fixed in the `next` branch of rcs, but compiling that is non-trivial. Here's my super hacky attempt at a recipe for rcs that supports `--HEAD`. It works fine for now but it's not ready for a pull request!

https://gist.github.com/aufflick/8280534e43678921d09c

**Comment by apjanke** [comment]
Even if you're not going to make a PR yet, want to put this on a branch on aufflick/homebrew? Makes it easier to see the diff and test it.

**Comment by aufflick** [comment]
Done ^

**Comment by pidloop** [comment]
Same error still occurring as of Dec 25 2015 with HomeBrew version 0.9.5. Was able to build rcs tools manually for now from rcs-5.9.4.tar.xz by hacking on src/base.h to replace line 44 from this 
 `#define exiting _Noreturn`
to this
 `#define exiting  // _Noreturn`

**Comment by mikemcquaid** [comment]
@pidloop Can you please submit this patch to the upstream developers of this project and add a link to the upstream patch submission and explanation of why the patch is needed in a comment in the formula file as a pull request. Thanks!

**Comment by wlad** [comment]
@pidloop @mikemcquaid Is there a reason this one-line patch hasn't made it to the formula?

**Comment by dunn** [comment]
> Is there a reason this one-line patch hasn't made it to the formula?

Someone needs to submit it upstream.

**Comment by mistydemeo** [comment]
This *was* fixed upstream, and applying the patch from the upstream git repo works for me. I migrated a copy of that commit, minus changelog changes, to Homebrew/patches, and I have a PR up here.

**Comment by wlad** [comment]
@mistydemeo Thanks!!

**Comment by mistydemeo** [comment]
Fixed, and added a 10.11 bottle while I was at it.
