### ISSUE TITLE
voms failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44040]
https://gist.github.com/0396db578aed71b62d5c

Can't find OpenSSL.

```
In file included from sslutils.c:36:
../../src/include/myproxycertinfo.h:29:10: fatal error: 'openssl/x509.h' file not found
#include <openssl/x509.h>
         ^
1 error generated.
make[2]: *** [libssl_utils_nog_la-sslutils.lo] Error 1
```

**Comment by apjanke** [comment]
Closing b/c I have a pending PR for this.
