### PR TITLE
binwalk: bump numpy

### LINKED ISSUE #43908: binwalk failed to build on 10.11
https://gist.github.com/c62c4135b0acd327a417

Fails to find `Python.h`.

```
compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -c'
clang: _configtest.c
_configtest.c:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
_configtest.c:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
failure.
```

Doesn't appear 10-11-specific. I'm getting the same error on 10.9.5.

### PR DESCRIPTION
**Pull request by tdsmith**
Fixes #43908.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by UniqMartin** [comment]
Would be great to see this fix merged. Works for me and I haven't discovered any downsides yet.

**Comment by tdsmith** [comment]
@BrewTestBot test this please

**Comment by tdsmith** [comment]
Done; thanks for the nudge.

**Comment by UniqMartin** [comment]
You're welcome. Thanks for reducing the number of local changes I have to keep track of! :+1:
