### ISSUE TITLE
net-snmp failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43930]
https://gist.github.com/d71b8876f8124cbd10b6

```
libtool: compile:  clang -I../../include -I. -I../../agent -I../../agent/mibgroup -I../../snmplib -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -g -O2 -Udarwin15 -Ddarwin15=darwin15 -c mibII/tcp.c  -fno-common -DPIC -o mibII/.libs/tcp.o
mibII/tcp.c:343:21: error: use of undeclared identifier 'TCPTV_MIN'
        ret_value = TCPTV_MIN / PR_SLOWHZ * 1000;
                    ^
mibII/tcp.c:351:21: error: use of undeclared identifier 'TCPTV_REXMTMAX'
        ret_value = TCPTV_REXMTMAX / PR_SLOWHZ * 1000;
                    ^
2 errors generated.
make[2]: *** [mibII/tcp.lo] Error 1
```

Looks like it might be an upstream per-OS configuration issue, [like this similar bug](http://sourceforge.net/p/net-snmp/bugs/2275/)

Same thing [happened for 10.10](https://sourceforge.net/p/net-snmp/bugs/2504/) and the workaround was to patch it in the formula. (#34904)

**Comment by apjanke** [comment]
Formula fix in https://github.com/apjanke/homebrew/tree/net-snmp-10_11; will make it a PR after testing is finished. (This formula takes a long time to build.)

**Comment by DomT4** [comment]
Closing in favour of #43931.
