### ISSUE TITLE
homebrew/php/php55-memcached failed to build on 10.11.2

### ISSUE THREAD

**Issue by adambisek** [Homebrew/homebrew#47759]
<pre>
brew install homebrew/php/php55-memcached
==> Installing php55-memcached from homebrew/homebrew-php
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:779:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:125:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:124:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:124:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:102:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:188:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:133:in `<main>'
</pre>

Gist logs are empty.

**Comment by adambisek** [comment]
Sorry, homebrew was broken after update to El Capitan.
