### PR TITLE
tesseract 3.04.01

### LINKED ISSUE #49352: tesseract fails to build on 10.11.3
Gist available here: https://gist.github.com/3abe4fba53f09f29ced5

It looks like an issue with OpenCL support, given that the file failing to build is openclwrapper.cpp.

Thank you!

### PR DESCRIPTION
**Pull request by ilovezfs**
Upstream fixed the following build error when using --with-opencl:

  In file included from openclwrapper.cpp:10:
  ./openclwrapper.h:2:10: fatal error: 'allheaders.h' file not found
  #include "allheaders.h"
           ^
  1 error generated.
  make[1]: *** [openclwrapper.lo] Error 1
  make: *** [install-recursive] Error 1

Closes #49352

### CODE REVIEW

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/81ef3376cf177220b79b0cf1b9f3a0e314e0b8d2. Thank you once again @ilovezfs!
