### ISSUE TITLE
Qt 5.5.1 HEAD Failing to Build on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by dagoodma** [Homebrew/homebrew#45207]
Hello,

I just did a clean install of Yosemite today, and then upgraded to 10.10.5. I installed XCode Version 7.0.1 (7A1001). I also ran  `xcode-select --install` to install the command line tools.

When I install Qt with `brew install qt5 --HEAD -vd --with-developer --with-examples`, I see the following errors during `make`:

	cd planets/ && ( test -e Makefile || /private/tmp/qt520151020-35208-lchefh/qtbase/bin/qmake /private/tmp/qt520151020-35208-lchefh/qtcanvas3d/examples/canvas3d/canvas3d/threejs/planets/planets.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile
	make[4]: Nothing to be done for `first'.
	( test -e Makefile.qml || /private/tmp/qt520151020-35208-lchefh/qtbase/bin/qmake /private/tmp/qt520151020-35208-lchefh/qtsensors/examples/sensors/grue/qml.pro -o Makefile.qml ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.qml
	qversittimezonehandler.h:89:62: error: parameter type 'QtVersitOrganizer::QVersitTimeZoneHandler' is an abstract class
	Q_DECLARE_INTERFACE(QtVersitOrganizer::QVersitTimeZoneHandler, QT_VERSIT_TIMEZONE_HANDLER_INTERFACE)
	                                                             ^
	qversittimezonehandler.h:68:23: note: unimplemented pure virtual method 'convertTimeZoneToUtc' in 'QVersitTimeZoneHandler'
	    virtual QDateTime convertTimeZoneToUtc(const QDateTime& datetime, const QString& timeZoneName) = 0;
	                      ^
	qversittimezonehandler.h:82:23: note: unimplemented pure virtual method 'convertUtcToTimeZone' in 'QVersitTimeZoneHandler'
	    virtual QDateTime convertUtcToTimeZone(const QDateTime& datetime, const QString& timeZoneName) = 0;
	                      ^
	qversittimezonehandler.h:89:64: error: expected parameter declarator
	Q_DECLARE_INTERFACE(QtVersitOrganizer::QVersitTimeZoneHandler, QT_VERSIT_TIMEZONE_HANDLER_INTERFACE)
	                                                               ^
	qversittimezonehandler.h:87:46: note: expanded from macro 'QT_VERSIT_TIMEZONE_HANDLER_INTERFACE'
	#define QT_VERSIT_TIMEZONE_HANDLER_INTERFACE "org.qt-project.Qt.QVersitTimeZoneHandler"
	                                             ^
	qversittimezonehandler.h:89:64: error: expected ')'
	qversittimezonehandler.h:87:46: note: expanded from macro 'QT_VERSIT_TIMEZONE_HANDLER_INTERFACE'
	#define QT_VERSIT_TIMEZONE_HANDLER_INTERFACE "org.qt-project.Qt.QVersitTimeZoneHandler"
	                                             ^
	qversittimezonehandler.h:89:20: note: to match this '('
	Q_DECLARE_INTERFACE(QtVersitOrganizer::QVersitTimeZoneHandler, QT_VERSIT_TIMEZONE_HANDLER_INTERFACE)
	                   ^
	qversittimezonehandler.h:91:7: error: expected function body after function declarator
	#endif
	      ^
	make[4]: Nothing to be done for `first'.
	cd qtwebchannel/ && ( test -e Makefile || /private/tmp/qt520151020-35208-lchefh/qtbase/bin/qmake /private/tmp/qt520151020-35208-lchefh/qtwebchannel/qtwebchannel.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile
	4 errors generated.
	make[3]: *** [.obj/header_qversittimezonehandler.o] Error 1
	make[3]: *** Waiting for unfinished jobs....

PS. Before, I tried installing without the command line tools and only xcode 7. I saw a different error about a missing POSIX header. Then, I ran `xcode-select --install` and got further along, but ran into the above error. I am going to try and build without --HEAD.

**Comment by mikemcquaid** [comment]
We can't support compilation errors with `--HEAD`, unfortunately.

**Comment by DomT4** [comment]
Yeah, there's not much we can do here I'm afraid.

> I am going to try and build without --HEAD.

Did this build okay?

**Comment by dagoodma** [comment]
Yes. It builds fine without --HEAD. Everything seems to be working. Thanks. =)
