### ISSUE TITLE
root failed to build on 10.7

### ISSUE THREAD

**Issue by krod0era** [Homebrew/homebrew#35580]
this is the error I receive when trying to install:
==> Installing root from homebrew/homebrew-science
==> Downloading ftp://root.cern.ch/root/root_v5.34.24.source.tar.gz
Already downloaded: /Library/Caches/Homebrew/root-5.34.24.tar.gz
==> Patching
==> ./configure macosx64 --all --enable-builtin-glew --enable-builtin-freetype --p
==> make
   URL dataServer(fFile->GetDataServer());
                  ~~~~~  ^
1 error generated.
make: *** [net/netxng/src/TNetXNGFile.o] Error 1
make: *** Waiting for unfinished jobs....

I can't find any help on this.  Any assistance would be greatly appreciated.  I've installed ROOT with homebrew successfully before...

and here is the gist:  https://gist.github.com/2873cfe44fe1583f023d

**Comment by mistydemeo** [comment]
The error:

```
clang++ -O2 -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Iinclude -DR__HAVE_CONFIG       -pthread -I/usr/local/include/xrootd -Wno-unused-parameter -Wno-shadow -o net/netxng/src/TNetXNGFil
eStager.o -c /private/tmp/root-liQIcG/root/net/netxng/src/TNetXNGFileStager.cxx
/private/tmp/root-liQIcG/root/net/netxng/src/TNetXNGFile.cxx:670:26: error: no member named 'GetDataServer' in 'XrdCl::File'
   URL dataServer(fFile->GetDataServer());
                  ~~~~~  ^
1 error generated.
```

**Comment by mistydemeo** [comment]
Looks like this is a known issue with the most recent version of xrootd: https://sft.its.cern.ch/jira/browse/ROOT-6998? There's a proposed patch.

**Comment by mistydemeo** [comment]
Should be fixed now - can you `brew update` and try again?

**Comment by krod0era** [comment]
fixed.  thanks very much!
