### ISSUE TITLE
bulk_extractor failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43912]
https://gist.github.com/56a26032bc6ccdc10d57

Can't find OpenSSL.

```
In file included from ../src/be13_api/feature_recorder.h:60:
./dfxml/src/hash_t.h:60:2: error: OpenSSL required for hash_t.h
#error OpenSSL required for hash_t.h
 ^
```

**Comment by DomT4** [comment]
Closing in favour of #43913.
