### ISSUE TITLE
"  'brew install hdf5 opencv' failed to build on 10.10"

### ISSUE THREAD

**Issue by AnushaManila** [Homebrew/homebrew#46857]
Error : undefined method `desc' for Formulary::Formulae::Hdf5:Class

Could anyone help to solve this issue?

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-science#3108
