### ISSUE TITLE
Doxygen failed to build on 10.10.3

### ISSUE THREAD

**Issue by agatti** [Homebrew/homebrew#39642]
After updating LLVM to 3.6.0 doxygen compiled with `--with-clang-static` needed to be rebuilt, and it fails to compile with the new LLVM version.

The logs for the formula are available at https://gist.github.com/dad0c8c34b8b43fb3136

Thank you!

**Comment by acgetchell** [comment]
It works if the --with-libclang option is not used.

┌─[adam][Hapkido][~]
└─▪ brew install doxygen --with-doxywizard --with-graphviz
==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/doxygen-1.8.9.1.tar.gz
==> Patching
patching file addon/doxywizard/Makefile.in
Hunk #1 succeeded at 31 (offset 1 line).
patching file configure
Hunk #1 succeeded at 583 (offset 5 lines).
==> ./configure --prefix /usr/local/Cellar/doxygen/1.8.9.1 --with-doxywizard
==> make
==> make MAN1DIR=share/man/man1 install
🍺  /usr/local/Cellar/doxygen/1.8.9.1: 7 files, 15M, built in 47 seconds

**Comment by agatti** [comment]
@acgetchell, what you report was indeed what brought me to rebuild doxygen and find out it wouldn't build anymore after the 3.5->3.6 upgrade.  Unfortunately the codebase I have to run doxygen requires it do use clang to be able to be able to generate useable documentation.

**Comment by DomT4** [comment]
Is this still an issue? It may need reporting upstream if it is.

**Comment by agatti** [comment]
Still is:

<pre>
~ ❯❯❯ brew update                                                                                                                                                                                                                           ⏎
Updated Homebrew from 8da69867 to bf20f49a.
==> Updated Formulae
baresip	    fzf		jruby	    libre	natalie	    plt-racket	pwsafe	    syncthing	yara
~ ❯❯❯ brew install doxygen --with-graphviz --with-libclang
==> Installing doxygen dependency: llvm
==> Downloading http://llvm.org/releases/3.6.1/llvm-3.6.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.6.1/libcxx-3.6.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.6.1/cfe-3.6.1.src.tar.xz
######################################################################## 100.0%
==> Downloading http://llvm.org/releases/3.6.1/clang-tools-extra-3.6.1.src.tar.xz
######################################################################## 100.0%
==> cmake -G Unix Makefiles /private/tmp/llvm20150622-80850-1084csm/llvm-3.6.1.src -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/llvm/3.6.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=L
==> make
==> make install
==> make -C projects/libcxx install DSTROOT=/usr/local/Cellar/llvm/3.6.1 SYMROOT=/private/tmp/llvm20150622-80850-1084csm/llvm-3.6.1.src/projects/libcxx
==> Caveats
LLVM executables are installed in /usr/local/opt/llvm/bin.
Extra tools are installed in /usr/local/opt/llvm/share/llvm.

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/llvm/lib
    CPPFLAGS: -I/usr/local/opt/llvm/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/llvm/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/llvm.pth
==> Summary
🍺  /usr/local/Cellar/llvm/3.6.1: 1486 files, 458M, built in 17.4 minutes
==> Installing doxygen
==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.9.1.src.tar.gz
######################################################################## 100.0%
==> Patching
patching file addon/doxywizard/Makefile.in
Hunk #1 succeeded at 31 (offset 1 line).
patching file configure
Hunk #1 succeeded at 583 (offset 5 lines).
==> ./configure --prefix /usr/local/Cellar/doxygen/1.8.9.1 --with-libclang-static
==> make
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../bin/doxygen] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Doxygen failed to build on 10.10.3 (https://github.com/Homebrew/homebrew/issues/39642)
</pre>

**Comment by DomT4** [comment]
Has anyone reported it to `doxygen`?

**Comment by acgetchell** [comment]
Doxygen's repo on GitHub doesn't have issues enabled:

https://github.com/doxygen/doxygen

**Comment by jacknagel** [comment]
https://bugzilla.gnome.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&product=doxygen

**Comment by acgetchell** [comment]
Bug submitted:

https://bugzilla.gnome.org/show_bug.cgi?id=751522

**Comment by DomT4** [comment]
If upstream's comments in that thread are correct, this will have been fixed by https://github.com/Homebrew/homebrew/commit/4650b30a2a7d43a179a20324112735ee29c7e9a3.

**Comment by acgetchell** [comment]
Yes, fixed.

┌─[adam][hapkido][~]
└─▪ brew install doxygen --with-doxywizard --with-graphviz --with-libclang
==> Downloading http://ftp.stack.nl/pub/users/dimitri/doxygen-1.8.10.src.tar.gz
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL
==> make
Warning: doxygen dependency qt was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/doxygen/1.8.10: 9 files, 14M, built in 43 seconds
