### ISSUE TITLE
SDL2 failed to build on 10.6

### ISSUE THREAD

**Issue by Caperr** [Homebrew/homebrew#37837]
Hello,
I'm attempting to install SDL2 (so that I can run ppsspp), and brew returns errors (I may be wrong with this) mentioning SDL_cocoamousetap and SDL_cocoagl, unfortunately I have no idea how to deal with such errors.
If you would like a basic screenshot of my terminal log: http://is.gd/sKxRgK
And here is my Gist: https://gist.github.com/9d274374aa48934b84f2

Apologies if this is a small issue, I'm virtually a complete newbie to BASH/shell etc, minimal knowledge.
Thanks in advance :)
- Jasper

Running early 2008 macbook 4,1
OSX 10.6.8

**Comment by jacknagel** [comment]
```
/private/tmp/sdl220150318-297-18500uu/SDL2-2.0.3/src/video/cocoa/SDL_cocoaopengl.m: In function 'Cocoa_GL_GetDrawableSize':
/private/tmp/sdl220150318-297-18500uu/SDL2-2.0.3/src/video/cocoa/SDL_cocoaopengl.m:351: error: incompatible types in assignment
```

Guessing it's a 10.6 incompatibility.

**Comment by jacknagel** [comment]
According to http://forums.libsdl.org/viewtopic.php?p=43928&sid=3ff9a0ad0f06c6afacaa2535e6d1ff2e, one needs the 10.7 SDK to build SDL 2.0.3.

**Comment by Caperr** [comment]
Ah, thank you!

**Comment by nijikon** [comment]
Is this still an issue?

**Comment by nijikon** [comment]
@Caperr Can you please check if this is still an issue?

**Comment by DomT4** [comment]
I doubt this Issue is going to spring back into life. I suspect it's still the case that this fails to build on 10.6 and below. We have VMs available, I'll try to set one up later and check.

**Comment by nijikon** [comment]
So maybe let's just close it and take a look when it comes up again.

**Comment by DomT4** [comment]
It seems kinder to check first, given if it is broken we can just stick an OS X version check in.

**Comment by mistydemeo** [comment]
This was fixed in Tigerbrew via 81d2c80f8b771b4eb757a1a4fd458779b00654ce; it works on 10.4 and 10.5 using that.

**Comment by DomT4** [comment]
@mistydemeo Thanks Misty. Worth adding to Homebrew for 10.6 as well in your opinion, or?

**Comment by mistydemeo** [comment]
Yeah, I think that'd be a good idea.

**Comment by mistydemeo** [comment]
PR at #47944.
