### ISSUE TITLE
libav failed to build on 10.9.5

### ISSUE THREAD

**Issue by eliukblau** [Homebrew/homebrew#48309]
libavcodec/libvpxenc.c:73:6: error: use of undeclared identifier 'VP8E_UPD_ENTROPY'

gist-logs:
https://gist.github.com/5f5d07ce09776f5e6974

**Comment by mistydemeo** [comment]
Looks like those were removed from libvpx in a recent release: https://github.com/webmproject/libvpx/commit/a046f56491b2c2a383491d0b5eae032c57d91eb9

**Comment by eliukblau** [comment]
@mistydemeo Thank you :D
