### ISSUE TITLE
qt failed to build on 10.11

### ISSUE THREAD

**Issue by mistydemeo** [Homebrew/homebrew#40585]
https://gist.github.com/eb6c70d66085fb3ce837

```
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20150610-44719-1qwdhre/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qgraphicssystem_mac.o painting/qgraphicssystem_mac.cpp
painting/qpaintengine_mac.cpp:345:19: error: use of undeclared identifier 'CMGetProfileByAVID'
    CMError err = CMGetProfileByAVID((CMDisplayIDType)displayID, &displayProfile);
                  ^
painting/qpaintengine_mac.cpp:348:9: error: use of undeclared identifier 'CMCloseProfile'
        CMCloseProfile(displayProfile);
        ^
```

**Comment by tdsmith** [comment]
Looks like deprecated API: https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/ColorSync_Manager/index.html#//apple_ref/c/func/CMCloseProfile

**Comment by mikemcquaid** [comment]
Qt note: to stand any hope of this being fixed you'll need to submit a patch to their Gerrit. I wouldn't even bother with a bug report at this point.

**Comment by firedev** [comment]
Bye capybara?

**Comment by DomT4** [comment]
Moved to tracking in #40837.

**Comment by dvcrn** [comment]
Any workarounds on this?

**Comment by DomT4** [comment]
None. You're welcome to report it upstream to Qt as a bug, but I wouldn't expect quick action unless someone submits a patch as well.

**Comment by Snwspeckle** [comment]
I'm having the same problem when I try to install wireshark with the command:
`brew install wireshark --with-qt`
Here's my gist: https://gist.github.com/anonymous/885e29e9f8c886b53b84

I'm also running 10.11.

**Comment by ejtttje** [comment]
Looks like there is a patch available here: https://gitlab.com/pteam/pteam-qtbase/commit/b06304e164ba47351fa292662c1e6383c081b5ca

**Comment by ejtttje** [comment]
Hmm, that patch is a bit outdated—won't apply as-is—but it does seem to have the right idea.
Here's an updated version: https://gist.github.com/ejtttje/7163a9ced64f12ae9444

**Comment by DomT4** [comment]
If you submit that as a bug report, or to their code review, and get some kind of response to the issue from Qt I'm happy to consider us adding it as a patch for >= 10.11.

**Comment by thiagomacieira** [comment]
The patch in http://code.qt.io/cgit/qt/qtbase.git/commit/?id=b06304e164ba47351fa292662c1e6383c081b5ca isn't outdated. It's too new: it was designed for Qt 5.2.

**Comment by mikemcquaid** [comment]
@thiagomacieira Is there any chance a back port would be accepted? Qt (4) is our 65th most downloaded package and once 10.11 ships significant numbers of people will be wanting to install it on 10.11.

**Comment by thiagomacieira** [comment]
No, there is none. Qt 4.8 will only receive security bugfixes and this does not qualify as such. Please keep a patch locally on homebrew instead.

**Comment by mikemcquaid** [comment]
@thiagomacieira Will there be any more security patch releases of Qt 4?

**Comment by thiagomacieira** [comment]
There might be. It's impossible to tell.

BTW, I urge you to never build using the -qt-libxxx options in 4.8 anymore. The bundled versions are too old. Insist on and require the system versions of those libraries.

**Comment by HYR** [comment]
Just FYI for those who are still coming across this issue. A simple update and upgrade now fixes the issue.

`$ brew update`
`$ brew upgrade qt`

(Note: be sure to accept Xcode's agreement if you hadn't already, otherwise the upgrade fails. Once accepted then `brew upgrade qt` works.)
