### ISSUE TITLE
fltk fails to build on 10.11

### ISSUE THREAD

**Issue by ejtttje** [Homebrew/homebrew#41581]
It's a fairly trivial error, due to using the 'enum' keyword in C++ when declaring an instance of that enum (shouldn't do that, just drop the enum)

Looks like FLTK has its own independent bug tracker, maybe someone else already has an account with them and can send this on upstream.

```
Compiling fl_symbols.cxx...
fl_line_style.cxx:38:13: error: elaborated type refers to a typedef
static enum CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;
            ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:33:26: note: declared here
typedef CF_ENUM(int32_t, CGLineCap) {
                         ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:128:88: note: expanded from macro 'CF_ENUM'
#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM)(__VA_ARGS__)
                                                                                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:111:45: note: expanded from macro '__CF_NAMED_ENUM'
#define __CF_NAMED_ENUM(_type, _name) _type _name; enum
                                            ^
fl_line_style.cxx:39:13: error: elaborated type refers to a typedef
static enum CGLineJoin fl_quartz_line_join_ = kCGLineJoinMiter;
            ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:25:26: note: declared here
typedef CF_ENUM(int32_t, CGLineJoin) {
                         ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:128:88: note: expanded from macro 'CF_ENUM'
#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM)(__VA_ARGS__)
                                                                                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:111:45: note: expanded from macro '__CF_NAMED_ENUM'
#define __CF_NAMED_ENUM(_type, _name) _type _name; enum
                                            ^
fl_line_style.cxx:113:15: error: elaborated type refers to a typedef
  static enum CGLineCap Cap[4] = { kCGLineCapButt, kCGLineCapButt, 
              ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:33:26: note: declared here
typedef CF_ENUM(int32_t, CGLineCap) {
                         ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:128:88: note: expanded from macro 'CF_ENUM'
#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM)(__VA_ARGS__)
                                                                                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:111:45: note: expanded from macro '__CF_NAMED_ENUM'
#define __CF_NAMED_ENUM(_type, _name) _type _name; enum
                                            ^
fl_line_style.cxx:115:15: error: elaborated type refers to a typedef
  static enum CGLineJoin Join[4] = { kCGLineJoinMiter, kCGLineJoinMiter, 
              ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:25:26: note: declared here
typedef CF_ENUM(int32_t, CGLineJoin) {
                         ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:128:88: note: expanded from macro 'CF_ENUM'
#define CF_ENUM(...) __CF_ENUM_GET_MACRO(__VA_ARGS__, __CF_NAMED_ENUM, __CF_ANON_ENUM)(__VA_ARGS__)
                                                                                       ^
/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:111:45: note: expanded from macro '__CF_NAMED_ENUM'
#define __CF_NAMED_ENUM(_type, _name) _type _name; enum
                                            ^
4 errors generated.
```

**Comment by ejtttje** [comment]
Hmm, doesn't look like I can attach a diff as a file here, but here's the update to fltk.rb to get it to build:

```
diff --git a/Library/Formula/fltk.rb b/Library/Formula/fltk.rb
index c2bc6da..abfcb3e 100644
--- a/Library/Formula/fltk.rb
+++ b/Library/Formula/fltk.rb
@@ -35,15 +35,42 @@ class Fltk < Formula
 end
 
 __END__
-diff --git a/src/Makefile b/src/Makefile
-index fcad5f0..5a5a850 100644
---- a/src/Makefile
-+++ b/src/Makefile
-@@ -360,7 +360,7 @@ libfltk_images.1.3.dylib: $(IMGOBJECTS) libfltk.1.3.dylib
+diff -ru fltk-1.3.3/src/Makefile fltk-1.3.3.patched/src/Makefile
+--- fltk-1.3.3/src/Makefile	2014-10-30 09:05:22.000000000 -0700
++++ fltk-1.3.3.patched/src/Makefile	2015-07-10 11:53:01.000000000 -0700
+@@ -360,7 +360,7 @@
  		-install_name $(libdir)/$@ \
- 		-current_version 1.3.1 \
+ 		-current_version 1.3.3 \
  		-compatibility_version 1.3.0 \
 -		$(IMGOBJECTS)  -L. $(LDLIBS) $(IMAGELIBS) -lfltk
 +		$(IMGOBJECTS)  -L. $(LDLIBS) $(IMAGELIBS) -lfltk $(LDFLAGS)
  	$(RM) libfltk_images.dylib
  	$(LN) libfltk_images.1.3.dylib libfltk_images.dylib
+ 
+Only in fltk-1.3.3.patched/src: Makefile.orig
+diff -ru fltk-1.3.3/src/fl_line_style.cxx fltk-1.3.3.patched/src/fl_line_style.cxx
+--- fltk-1.3.3/src/fl_line_style.cxx	2012-03-18 11:48:29.000000000 -0700
++++ fltk-1.3.3.patched/src/fl_line_style.cxx	2015-07-10 11:48:42.000000000 -0700
+@@ -35,8 +35,8 @@
+ 
+ #ifdef __APPLE_QUARTZ__
+ float fl_quartz_line_width_ = 1.0f;
+-static enum CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;
+-static enum CGLineJoin fl_quartz_line_join_ = kCGLineJoinMiter;
++static CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;
++static CGLineJoin fl_quartz_line_join_ = kCGLineJoinMiter;
+ static CGFloat *fl_quartz_line_pattern = 0;
+ static int fl_quartz_line_pattern_size = 0;
+ void fl_quartz_restore_line_style_() {
+@@ -110,9 +110,9 @@
+   DeleteObject(fl_current_xmap->pen);
+   fl_current_xmap->pen = newpen;
+ #elif defined(__APPLE_QUARTZ__)
+-  static enum CGLineCap Cap[4] = { kCGLineCapButt, kCGLineCapButt, 
++  static CGLineCap Cap[4] = { kCGLineCapButt, kCGLineCapButt, 
+                                    kCGLineCapRound, kCGLineCapSquare };
+-  static enum CGLineJoin Join[4] = { kCGLineJoinMiter, kCGLineJoinMiter, 
++  static CGLineJoin Join[4] = { kCGLineJoinMiter, kCGLineJoinMiter, 
+                                     kCGLineJoinRound, kCGLineJoinBevel };
+   if (width<1) width = 1;
+   fl_quartz_line_width_ = (float)width; 
```

**Comment by mikemcquaid** [comment]
@ejtttje Could you try and open a pull request to the upstream project and also for Homebrew? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by jmtatsch** [comment]
I added a --HEAD option for compiling fltk from trunk
https://github.com/Homebrew/homebrew/pull/44806
which seems to work on El Capitan.  However, ./configure for threads and libs fails because configure is not found. Running autoconf before fails due to some templates missing. Maybe someone more knowledgable with build systems can give a hint or two :)

**Comment by Bohdan-Khomtchouk** [comment]
I went directly into the file giving me the error (e.g., fl_line_style.cxx) and commented out the enum on every line that had an error, e.g.,

I changed:

`static enum CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;`

To:

`static /*enum*/ CGLineCap fl_quartz_line_cap_ = kCGLineCapButt;`

I repeated this for every line that the compiler threw an error on.  In my fl_line_style.cxx file, it was on lines 38, 39, 113, and 115.

Then I was finally able to run `make` successfully.

**Comment by mikemcquaid** [comment]
If someone can submit a pull-request with this fix and submit it upstream: we'd accept it.

**Comment by DomT4** [comment]
Part of me is tempted to say we'd find life easier temporarily switching to using the snapshot releases (and periodically update rather than using every one) for `fltk` and reverting to stable when the next stable is cut. We're already having to enforce that for El Cap because `devel` builds but `stable` does not.

**Comment by mikemcquaid** [comment]
@DomT4 :+1:
