### ISSUE TITLE
cdimgtools fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41267]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install cdimgtools
==> Installing dependencies for cdimgtools: libdvdcss, libdvdread
…
==> Installing cdimgtools
==> Downloading http://download.gna.org/cdimgtools/cdimgtools-0.3.tar.gz
######################################################################## 100,0%
==> ./configure --prefix=/usr/local/Cellar/cdimgtools/0.3
==> make install install-doc-man
2 errors generated.
make: *** [cssdec] Error 1
make: *** Waiting for unfinished jobs....
2 errors generated.
make: *** [dvdimgdecss] Error 1

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/c8fd7555fd52a24455d8

**Comment by bfontaine** [comment]
```
==> make install install-doc-man
clang  -DHAVE_CONFIG_H=1 \
		-g -O2  -o cssdec cssdec.c -ldvdcss
cssdec.c:106:29: error: use of undeclared identifier 'dvdcss_interface_2'
                          progname, progversion, dvdcss_interface_2 );
                                                 ^
cssdec.c:130:27: error: use of undeclared identifier 'dvdcss_interface_2'
          progname, progversion, dvdcss_interface_2 );
                                 ^
2 errors generated.
make: *** [cssdec] Error 1
```

Seems like it’s relying on `dvdcss_interface_2`, which has been removed from libdvdcss [two years ago](https://mailman.videolan.org/pipermail/libdvdcss-devel/2013-March/000940.html). We have `homebrew/versions/libdvdcss12` but depending on this raises another error.

**Comment by MikeRich88** [comment]
I am also getting this error on 10.9.5, so it's not just limited to 10.10.x FYI.

**Comment by mikemcquaid** [comment]
@bfontaine Sounds like a boneyard :sob:

**Comment by apjanke** [comment]
@bfontaine Out of curiosity, how long did it take you to run this "install-everything" test? I fired off a little script to do the same on OS X 10.11 last night, and it looks like it's going to take... a *while*.

**Comment by bfontaine** [comment]
@apjanke Two or three days, but it was only running ~8 hours per day.
