### ISSUE TITLE
pygobject3 failed to build on 10.6.8

### ISSUE THREAD

**Issue by uwehermann** [Homebrew/homebrew#34734]
```
 CC _gi_la-pygboxed.lo
In file included from pygi-error.h:26,
from gobjectmodule.c:40:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
In file included from pygi.h:30,
from pygboxed.c:29:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
make[2]: *** [_gi_la-pygboxed.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [_gi_la-gobjectmodule.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Full log: https://gist.github.com/anonymous/9df19cb5aeddebea3560

**Comment by uwehermann** [comment]
Any updates on this issue and/or ideas of how to fix?

**Comment by mikemcquaid** [comment]
@uwehermann I'm not sure I'm afraid, I don't have a 10.6 machine to test on :( @mistydemeo, any ideas?

**Comment by tdsmith** [comment]
This looks a lot like this issue on 10.10, though: https://github.com/Homebrew/homebrew/issues/36207

**Comment by tdsmith** [comment]
Upstream bug: https://bugzilla.gnome.org/show_bug.cgi?id=737874 and fix: https://github.com/GNOME/pygobject/commit/0de827190e7575f7e1e339337b78c7d6e46957b4#diff-773a35b1e299e5b904889eeb20d4f4d7

I guess compilers have different tolerances for the redefinition?

**Comment by tdsmith** [comment]
Should be fixed if you want to update and give this another spin.

**Comment by uwehermann** [comment]
Yup, the build is fixed now, thanks!
