### ISSUE TITLE
qt failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42370]
Failed on my 10.11 Public Beta 3 box (with no CLT).

https://gist.github.com/f73b850d742f9bee21a7

```
clang++ -c -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -fPIC -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_ARM_NEON_OPT=0 -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_HAVE_MMX -DQT_HAVE_3DNOW -DQT_HAVE_SSE -DQT_HAVE_MMXEXT -DQT_HAVE_SSE2 -DQT_HAVE_SSE3 -DQT_HAVE_SSSE3 -DQT_HAVE_SSE4_1 -DQT_HAVE_SSE4_2 -DQT_HAVE_AVX -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/unsupported/macx-clang-libc++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt20150802-82330-1dbd7fd/qt-everywhere-opensource-src-4.8.7/lib -o .obj/release-shared/qpaintengine_mac.o painting/qpaintengine_mac.cpp
painting/qpaintengine_mac.cpp:345:19: error: use of undeclared identifier 'CMGetProfileByAVID'
    CMError err = CMGetProfileByAVID((CMDisplayIDType)displayID, &displayProfile);
                  ^
painting/qpaintengine_mac.cpp:348:9: error: use of undeclared identifier 'CMCloseProfile'
        CMCloseProfile(displayProfile);
        ^
2 errors generated.
make[2]: *** [.obj/release-shared/qpaintengine_mac.o] Error 1
make[1]: *** [release] Error 2
make: *** [sub-gui-make_default-ordered] Error 2
```

**Comment by DomT4** [comment]
This one needs kicking upstream. I can't find any fix or bug report on the upstream trackers.

**Comment by jakepetroules** [comment]
As per [QTBUG-48079](https://bugreports.qt.io/browse/QTBUG-48079), only security-related patched will be added to Qt 4.8 from this point forward. Please deprecate the Qt 4 formula and encourage users to use `qt5` instead.

**Comment by mikemcquaid** [comment]
@jakepetroules When all software using Qt4 is ported to Qt5: sure.

**Comment by jakepetroules** [comment]
Deprecation tends to encourage that. ;)

**Comment by DomT4** [comment]
I'm pretty strongly considering marking Qt4 as "will not build" on 10.11 and above, but I'm not sold on the idea that upstreams are going to rush to switch over to Qt5 if they haven't already at this point.

**Comment by mikemcquaid** [comment]
@jakepetroules I don't think that's our job.

**Comment by timblechmann** [comment]
@jakepetroules you know that huge parts of kde are still based on qt4?

@mikemcquaid, if upstream refuses to fix this issue, homebrew might patch qt4 to forward-declare the removed functions as they will most likely still be in the binaries, but were only removed from the headers

**Comment by mikemcquaid** [comment]
> @mikemcquaid, if upstream refuses to fix this issue, homebrew might patch qt4 to forward-declare the removed functions as they will most likely still be in the binaries, but were only removed from the headers

Yeh, we'll need to work something out.

**Comment by DomT4** [comment]
Should be fixed by Mike inserting the backport that was floating around.

**Comment by apjanke** [comment]
Confirmed: `brew install --build-from-source qt` now works on my OS X 10.11 GM seed / Xcode 7 GM seed test box.
