### ISSUE TITLE
libopkele failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42684]
https://gist.github.com/17f26431409e5db195c5

Fails to locate OpenSSL.

```
Making install in lib
/bin/sh ../libtool --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.. -I../include/ -I../include/      -DNDEBUG   -g -O2 -c -o params.lo params.cc
libtool: compile:  clang++ -DHAVE_CONFIG_H -I.. -I../include/ -I../include/ -DNDEBUG -g -O2 -c params.cc  -fno-common -DPIC -o .libs/params.o
params.cc:4:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make[1]: *** [params.lo] Error 1
make: *** [install-recursive] Error 1
```
