### ISSUE TITLE
telepathy-gabble failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44014]
https://gist.github.com/4600fea16515f0419817

```
clang -DHAVE_CONFIG_H -I. -I.. -I../wocky   -Wall -Wextra -Wdeclaration-after-statement -Wshadow -Wstrict-prototypes -Wmissing-prototypes -Wsign-compare -Wnested-externs -Wpointer-arith -Wformat-security -Winit-self -Wno-missing-field-initializers -Wno-unused-parameter  -D_REENTRANT -I/usr/local/Cellar/glib/2.44.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.44.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/include/libxml2  -I/usr/local/Cellar/openssl/1.0.2d_1/include  -I.. -I.. -g -O2 -c wocky-bare-contact-test.c
wocky-test-sasl-auth-server.c:53:15: error: typedef redefinition with different types ('int (*)(void)' vs 'int (*)()')
typedef int (*sasl_callback_ft)(void);
              ^
/usr/include/sasl/saslplug.h:36:15: note: previous definition is here
typedef int (*sasl_callback_ft)(); // APPLE: remove void
              ^
1 error generated.
```

**Comment by DomT4** [comment]
Was boneyarded.
