### ISSUE TITLE
brew switch broken since 2350ab0

### ISSUE THREAD

**Issue by pmwheatley** [Homebrew/homebrew#40124]
```
$ brew switch xmlstarlet 1.6.1
Cleaning /usr/local/Cellar/xmlstarlet/1.6.1
Error: undefined method `directory?' for "xmlstarlet":String
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:205:in `from_rack'
/usr/local/Library/Homebrew/cmd/link.rb:52:in `keg_only?'
/usr/local/Library/Homebrew/cmd/switch.rb:43:in `switch'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by pmwheatley** [comment]
Opened PR #40126

**Comment by tamasflamich** [comment]
Thank you for this! Could you guys add some automated tests that covers the `switch` command to ensure this will not happen again?

**Comment by mikemcquaid** [comment]
@tamasflamich Could you try and open a pull request to do that? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!
