### ISSUE TITLE
openal-soft failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44059]
https://gist.github.com/4fde2f839763953219fc

Build failure. Don't know what's causing it.

```
/Applications/Xcode-7-GM.app/Contents/Developer/usr/bin/make -f CMakeFiles/common.dir/build.make CMakeFiles/common.dir/build
[  1%] Building C object CMakeFiles/common.dir/common/atomic.c.o
/usr/local/Library/ENV/4.3/clang  -D_GNU_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGE_FILES -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -std=c99  -O2 -fomit-frame-pointer -DNDEBUG -I/tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/include -I/tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0    -Winline -Wall -Wextra -fPIC -fvisibility=hidden -pthread -o CMakeFiles/common.dir/common/atomic.c.o   -c /tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/common/atomic.c
In file included from /tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/common/atomic.c:4:
/tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/include/atomic.h:19:10: error: address argument to atomic operation must be a pointer to _Atomic type ('volatile int *' invalid)
{ return atomic_exchange(ptr, newval); }
         ^               ~~~
/Applications/Xcode-7-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stdatomic.h:137:42: note: expanded from macro 'atomic_exchange'
#define atomic_exchange(object, desired) __c11_atomic_exchange(object, desired, __ATOMIC_SEQ_CST)
                                         ^
In file included from /tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/common/atomic.c:4:
/tmp/openal-soft20150916-62427-1of0crf/openal-soft-1.16.0/include/atomic.h:21:10: error: address argument to atomic operation must be a pointer to _Atomic type ('XchgPtr *' (aka 'void *volatile *') invalid)
{ return atomic_exchange(ptr, newval); }
         ^               ~~~
/Applications/Xcode-7-GM.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include/stdatomic.h:137:42: note: expanded from macro 'atomic_exchange'
#define atomic_exchange(object, desired) __c11_atomic_exchange(object, desired, __ATOMIC_SEQ_CST)
                                         ^
2 errors generated.
make[2]: *** [CMakeFiles/common.dir/common/atomic.c.o] Error 1
make[1]: *** [CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TimeDoctor** [comment]
I have a similar build failure though it isn't exactly the same, dupe? https://gist.github.com/anonymous/9c86cf2afa86dbf29e08

**Comment by DanielGibson** [comment]
According to the OpenAL-Soft developer, this problem is fixed in their git-repo.

The commit was http://repo.or.cz/openal-soft.git/commit/4b53d0e90cec08b4df06be22a9516f12ac5647f5 but it might not be possible to apply that change directly to 1.16.

**Comment by dunn** [comment]
Want to give it a try anyway? :D
