### ISSUE TITLE
pixman fails to build on 10.11

### ISSUE THREAD

**Issue by shaneburrell** [Homebrew/homebrew#41056]
pixman-mmx.c:100:20: error: constraint 'K' expects an integer constant expression
        : "y" (__A), "K" (__N)
                          ^~~

This is noted elsewhere on the web as issue.

GIST LOG

https://gist.github.com/84d27d46b06d29704b25

**Comment by shaneburrell** [comment]
--disable-mmx seems to get it to compile.

**Comment by jacknagel** [comment]
Can you report it to the pixman devs (if it hasn't been already)?

**Comment by shaneburrell** [comment]
I had submitted to there dev list. May want to change formula to disable mmx if clang. That seems to compile and was previously in the formula.

**Comment by shaneburrell** [comment]
Mail bounced back from there list. There is no other contact info I can to submit upgrade.  At one time the formula was disabling mmx which solves the issue. I've edited my local pixman.rb to revert that change.

**Comment by jacknagel** [comment]
Due to a recent breaking change in clang. This nacl thread explains it nicely. https://code.google.com/p/nativeclient/issues/detail?id=4201

**Comment by shaneburrell** [comment]
Actually it would appear Clang is correct and it just slipped by before and changes will have to be made in upstream code, patch, or disable mmx in the formula.

**Comment by jacknagel** [comment]
Yes, it is both correct _and_ a breaking change (code that compiled before no longer compiles).

**Comment by jacknagel** [comment]
We can't take any action here until there is a trackable upstream bug report, per our policy.

**Comment by shaneburrell** [comment]
For me it's fixed by adding the disable-mmx option.   I tried to submit to the list shown at pixman.org but both attempts I've sent have bounced back.  There are three contacts in the file in question but it appears they may not have worked on it since 2005.

 * Author:  Søren Sandmann (sandmann@redhat.com)
 * Minor Improvements: Nicholas Miell (nmiell@gmail.com)
 * MMX code paths for fbcompose.c by Lars Knoll (lars@trolltech.com)

**Comment by shaneburrell** [comment]
I sent an email to the last person to edit the file in the pixman git repo, detailing the problem.

**Comment by shaneburrell** [comment]
Got in touch with upstream and joined there mailing list (only way to submit issues). So I guess they are aware in the meantime anyone else needing this just add --disable-mmx.

**Comment by shaneburrell** [comment]
It appears this issue has been an issue for some time.  Should the formula just disable mmx if clang like it has in the past by default?  There has been a bug submission to the upstream list and its a problem that has been identified in the past and referenced in this post from 2014.

http://lists.freedesktop.org/archives/pixman/2012-February/001769.html

**Comment by shaneburrell** [comment]
#41075 Pull Request submitted to just disable mmx again.

**Comment by shaneburrell** [comment]
Fix applied.  Notified upstream.

**Comment by ranma42** [comment]
I started a thread on the pitman mailing list: http://lists.freedesktop.org/archives/pixman/2015-October/004080.html

**Comment by ranma42** [comment]
Ah, the label might be misleading: it's likely related to the Xcode version rather than to 10.11. I reproduced the problem on 10.10 using
```
$ clang --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
