### ISSUE TITLE
prepend() breaks brew on 10.8

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#46071]
This is a regression  caused by 4f1eec8 which uses "prepend," a feature only available in ruby >= 2. 

```
Josephs-MacBook-Pro:~ joe$ brew update
Updated Homebrew from c72171cf to a6dbfc20.
Updated 3 taps (homebrew/apache, homebrew/dupes, homebrew/versions).
==> New Formulae
devd            iproute2mac     shairport       tcpstat       
fprobe          psql2csv        sphinx-doc    
==> Updated Formulae
gl2ps                            lnav                           
glew                             mal4s                          
glide                            pgloader                       
gloox                            strongswan                     
gource                           tachyon                        
homebrew/dupes/grep (installed)  telegraf                       
homebrew/versions/jenkins-lts    volatility                     
jenkins                          wget (installed)               
keybase                          youtube-dl                     
libmaxminddb                   
Josephs-MacBook-Pro:~ joe$ brew upgrade
/usr/local/Library/Homebrew/compat/dependency_collector.rb:19: undefined method `prepend' for DependencyCollector:Class (NoMethodError)
	from /usr/local/Library/Homebrew/compat.rb:12:in `require'
	from /usr/local/Library/Homebrew/compat.rb:12
	from /usr/local/Library/Homebrew/global.rb:46:in `require'
	from /usr/local/Library/Homebrew/global.rb:46
	from /usr/local/Library/brew.rb:15:in `require'
	from /usr/local/Library/brew.rb:15
Josephs-MacBook-Pro:~ joe$ 
```
A temporary workaround is to revert 4f1eec8 but you'll need to reverse that later, so I won't provide instructions here to avoid creating additional issues for the Homebrew team.

**Comment by xu-cheng** [comment]
Sorry about that. It should be fixed now. You can update brew by `brew update --no-compat`.

**Comment by ilovezfs** [comment]
@xu-cheng Yup, thanks. Fix confirmed

```
Josephs-MacBook-Pro:local joe$ brew update
/usr/local/Library/Homebrew/compat/dependency_collector.rb:19: undefined method `prepend' for DependencyCollector:Class (NoMethodError)
	from /usr/local/Library/Homebrew/compat.rb:12:in `require'
	from /usr/local/Library/Homebrew/compat.rb:12
	from /usr/local/Library/Homebrew/global.rb:46:in `require'
	from /usr/local/Library/Homebrew/global.rb:46
	from /usr/local/Library/brew.rb:15:in `require'
	from /usr/local/Library/brew.rb:15
Josephs-MacBook-Pro:local joe$ brew update --no-compat
Updated Homebrew from a6dbfc20 to 5fe6087d.
No changes to formulae.
Josephs-MacBook-Pro:local joe$ brew update
Already up-to-date.
Josephs-MacBook-Pro:local joe$ brew upgrade
Josephs-MacBook-Pro:local joe$ 
```
