### ISSUE TITLE
cdimgtools failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42380]
On 10.11 Public Beta 3.

https://gist.github.com/f4e39a63bbaffe87f0ee

```
clang  -DHAVE_CONFIG_H=1 \
		-g -O2  -o cssdec cssdec.c -ldvdcss
cssdec.c:106:29: error: use of undeclared identifier 'dvdcss_interface_2'
                          progname, progversion, dvdcss_interface_2 );
                                                 ^
cssdec.c:130:27: error: use of undeclared identifier 'dvdcss_interface_2'
          progname, progversion, dvdcss_interface_2 );
                                 ^
2 errors generated.
make: *** [cssdec] Error 1
```

**Comment by bfontaine** [comment]
Seems to be the same issue as #41267.

**Comment by DomT4** [comment]
Yeah, not an 10.11 exclusive sadly.
