### ISSUE TITLE
proxychains-ng failed to build on 10.11

### ISSUE THREAD

**Issue by willin** [Homebrew/homebrew#43967]
```
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/project/proxychains-ng/proxychains
Already downloaded: /Library/Caches/Homebrew/proxychains-ng-4.10.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/proxychains-ng/4.10 --sysconfdir=/usr/loc
==> make
src/libproxychains.c:21:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [src/libproxychains.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

XCode Installed

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by mikemcquaid** [comment]
READ THIS: https://git.io/brew-troubleshooting

**Comment by willin** [comment]
```
015-09-15 18:14:58 +0800

make

clang -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/Cellar/proxychains-ng/4.10/lib\" -DSYSCONFDIR=\"/usr/local/Cellar/proxychains-ng/4.10/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/nameinfo.o src/nameinfo.c
printf '#define VERSION "%s"\n' "$(sh tools/version.sh)" > src/version.h
clang -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/Cellar/proxychains-ng/4.10/lib\" -DSYSCONFDIR=\"/usr/local/Cellar/proxychains-ng/4.10/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/core.o src/core.c
clang -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/Cellar/proxychains-ng/4.10/lib\" -DSYSCONFDIR=\"/usr/local/Cellar/proxychains-ng/4.10/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/common.o src/common.c
clang -DSUPER_SECURE -Wall -O0 -g -std=c99 -D_GNU_SOURCE -pipe  -DIS_MAC=1 -DLIB_DIR=\"/usr/local/Cellar/proxychains-ng/4.10/lib\" -DSYSCONFDIR=\"/usr/local/Cellar/proxychains-ng/4.10/etc\" -DDLL_NAME=\"libproxychains4.dylib\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
src/nameinfo.c:1:10: fatal error: 'sys/socket.h' file not found
src/core.c:18:10: fatal error: 'stdio.h' file not found
#include <sys/socket.h>
         ^
#include <stdio.h>
         ^
src/common.c:2:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>
         ^
1 error generated.
1 error generated.
make: *** [src/nameinfo.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [src/common.o] Error 1
1 error generated.
make: *** [src/core.o] Error 1
src/libproxychains.c:21:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
make: *** [src/libproxychains.o] Error 1

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: a2a72b4d6290ce186f3d02a163f58ae37b11c6c9
Last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.11-x86_64
Xcode: 6.4
CLT: N/A
GCC-4.2: build 0
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /System/Library/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.11
HOMEBREW_SDKROOT:
PATH: /usr/local/Library/ENV/4.3:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by mikemcquaid** [comment]
Please run `brew gist-logs proxychains-ng` and paste a link in this issue. Thanks!

**Comment by willin** [comment]
https://gist.github.com/de9406ebb0c77e4f2b4a

**Comment by DomT4** [comment]
Your Xcode is too old. You *need* to be running Xcode 7 on 10.11 at this point. Builds fine here with the required Xcode.

**Comment by willin** [comment]
https://gist.github.com/736d665fc9754a3d055b 

no use

**Comment by willin** [comment]
reopen

**Comment by DomT4** [comment]
Your Xcode is still pointing at 6.4. `sudo xcode-select --switch` to the correct path.
