### ISSUE TITLE
qt5 5.5.0 fails to build on OSX 10.11

### ISSUE THREAD

**Issue by henrik242** [Homebrew/homebrew#42014]
This is the last thing that happens before failing:

    mv -f QtNetwork ../../lib/QtNetwork.framework/Versions/5/QtNetwork
    ln -s Versions/Current/QtNetwork ../../lib/QtNetwork.framework/QtNetwork
    make[1]: *** [sub-src-make_first] Error 2
    make: *** [module-qtbase-make_first] Error 2

And here's the full log: http://pastebin.ca/3071408

**Comment by DomT4** [comment]
I'm not at all surprised on this. Both the Qt formulae often have a breakage party on unreleased OS X versions.

You'll need to check the upstream code review & bug trackers to see if they're aware, and then it may be worth filing an issue with them (Although be aware, Qt can tend to let stuff sit on the tracker for a *long* time).

**Comment by henrik242** [comment]
OK, created a clone of this issue @ https://bugreports.qt.io/browse/QTBUG-47383

**Comment by apjanke** [comment]
It's still failing for me on 10.11 Public Beta 2 and 3 (no CLT), with a different-looking error. 

```
qcocoacursor.mm:76:20: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef e = CGEventCreateMouseEvent(0, kCGEventMouseMoved, pos, 0);
                   ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
26 warnings and 1 error generated.
make[5]: *** [.obj/qcocoacursor.o] Error 1
make[5]: *** Waiting for unfinished jobs....
```

No idea what to do about the error. Here are the logs. https://gist.github.com/apjanke/4b452b4ccc1e58402e4a

**Comment by DomT4** [comment]
Someone needs to try `brew install qt5 --HEAD` to see if the problem still exists upstream. It's possible they've added more patches since which we need to find and adopt. I'll take a look in a couple days if nobody beats me to it.

**Comment by apjanke** [comment]
Trying `brew install qt5 --HEAD` now. Will post results when done.

**Comment by DomT4** [comment]
Thanks @apjanke, Appreciate the help on this. Qt5 is a horrible thing to build from source sadly.

**Comment by tloszko** [comment]
Have exactly same issue as @apjanke, --HEAD didn't help~

**Comment by apjanke** [comment]
I'm still getting a failure, albeit with a different error, on `--HEAD`.

```

/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -O2 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -fno-exceptions -Wall -W -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I../../../lib/QtCore.framework/Headers -I.moc -I../../../mkspecs/macx-clang -F/private/tmp/qt520150802-22045-1iqubxg/qtbase/lib -o .obj/dotgraph.o dotgraph.cpp
/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -c -pipe -O2 -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -fno-exceptions -Wall -W -fPIC -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_NO_TSLIB -DQT_NO_LIBINPUT -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I. -I../../../lib/QtCore.framework/Headers -I.moc -I../../../mkspecs/macx-clang -F/private/tmp/qt520150802-22045-1iqubxg/qtbase/lib -o .obj/lalr.o lalr.cpp
lalr.cpp:241:1: error: declaration of anonymous struct must be a definition
struct _Nullable: public std::unary_function<Name, bool>
^
lalr.cpp:241:56: error: expected unqualified-id
struct _Nullable: public std::unary_function<Name, bool>
                                                       ^
lalr.cpp:303:98: error: expected expression
          NameList::iterator nn = std::find_if (rule->rhs.begin (), rule->rhs.end (), std::not1 (_Nullable (this)));
                                                                                                 ^
lalr.cpp:638:107: error: expected expression
                  NameList::iterator first_not_nullable = std::find_if (dot, rule->rhs.end (), std::not1 (_Nullable (this)));
                                                                                                          ^
4 errors generated.
make[3]: *** [.obj/lalr.o] Error 1
make[2]: *** [sub-qlalr-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```

Logs here: https://gist.github.com/apjanke/53b2cbf92759d41fe98c

**Comment by DomT4** [comment]
> I'm still getting a failure, albeit with a different error

Heh, that's *literally* the known upstream failure that our patch for `stable do` fixes. Apparently, looking through Qt's Git repo, they're no longer pushing changes to the branches other than `dev`, which makes our `head` a bit pointless.

**Comment by jaeyeun97** [comment]
@DomT4  I realized that your patch fixes the problem by @apjanke. That is not upstream yet, and is not even in qt project. There also needs to be another fix about SDKROOTs that I just created a pull request for. With all this the formula should work fine.

Do you know anything about contributing to qt upstream? It looks a bit... complicated.

**Comment by DomT4** [comment]
> That is not upstream yet, and is not even in qt project.

No, It seems they've stopped pushing to Git very often. It all looks to be handled primarily on their [Gerrit Codereview](https://codereview.qt-project.org/) which is one of the least fun interfaces ever to try and find applicable fixes on.

**Comment by mhenrixon** [comment]
This seems to work for me - http://www.ahnbk.com/?p=325

**Comment by mikemcquaid** [comment]
Still confirmed broken here. Should be fixed by https://github.com/Homebrew/homebrew/pull/42452.

**Comment by DomT4** [comment]
Believe this was resolved by https://github.com/Homebrew/homebrew/commit/7d6658232bd2743a957219c480a3d137a084d851.

**Comment by drhalftone** [comment]
Did you upgrade Xcode?  Doing so will delete all SDKs less than 10.11.  So if you did, then you need to get the 10.10 SDK from one of your macs that you haven't had a chance to upgrade.  Take that SDK and place it with your 10.11 SDK.  That should fix your Qt issues.
