### ISSUE TITLE
fbida failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42489]
https://gist.github.com/20ab90768cbab91de566

Looks like same issue as #10801 recurring.

```
exiftran.c:17:10: fatal error: 'transupp.h' file not found
#include "transupp.h"           /* Support routines for jpegtran */
```

**Comment by DomT4** [comment]
No longer seems to be an issue against the Xcode 7 GM:

```
==> Finishing up
ln -s ../Cellar/fbida/2.10/bin/exiftran exiftran
ln -s ../../../Cellar/fbida/2.10/share/man/man1/exiftran.1 exiftran.1
==> Summary
🍺  /usr/local/Cellar/fbida/2.10: 7 files, 92K, built in 24 seconds
```

**Comment by apjanke** [comment]
Works for me too now, with Xcode 7 GM.
