### ISSUE TITLE
redis failed to build on 10.7

### ISSUE THREAD

**Issue by abr4xas** [Homebrew/homebrew#36843]
```bash
abr4xas@TMA: ~                                                                                                                                                     21:53
> brew install redis
==> Downloading http://download.redis.io/releases/redis-2.8.19.tar.gz
Already downloaded: /Library/Caches/Homebrew/redis-2.8.19.tar.gz
==> make -C /private/tmp/redis-9pCamI/redis-2.8.19/src CC=clang
      _zrealloc in zmalloc.o
      _zfree in zmalloc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [redis-cli] Error 1
```

Gist: https://gist.github.com/anonymous/d4f0194eeeed4ad47f80

**Comment by jacknagel** [comment]
>Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.

Please address this warning
