### ISSUE TITLE
erlang failed to build on 10.9.5

### ISSUE THREAD

**Issue by grep0** [Homebrew/homebrew#35382]
Failed to build erlang 17.4 in a custom directory.

```
In file included from wxe_main.cpp:24:
./wxe_impl.h:28:10: fatal error: 'wx/glcanvas.h' file not found
#include <wx/glcanvas.h>
         ^
wxe_impl.cpp:24:10: fatal error: 'wx/wx.h' file not found
#include <wx/wx.h>
         ^
1 error generated.
```

The wx installation is ok, required header files exist:
```
$ ls /opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0/wx/glcanvas.h
/opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0/wx/glcanvas.h
$ ls /opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wx.h
/opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0/wx/wx.h
```
Full logs:
https://gist.github.com/anonymous/472814056bd766b125a8

**Comment by grep0** [comment]
@Kielan - not my case:
```
$ brew install wxmac
Warning: wxmac-3.0.2 already installed
```
That failed command line
```
$ clang++ -c -Werror=return-type  -g -Wall -fPIC -m64 -g -O2 -mmacosx-version-min=10.9 -Wno-deprecated-declarations -fno-strict-aliasing  -D_MACOSX -D_THREAD_SAFE -D_REENTRANT -I/opt/homebrew/Cellar/wxmac/3.0.2/lib/wx/include/osx_cocoa-unicode-3.0 -I/opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__    -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DSIZEOF_VOID_P=8 -DHAVE_OPENGL_GL_H=1 -DHAVE_OPENGL_GLU_H=1 -DHAVE_GL_SUPPORT=1 -DHAVE_GLINTPTR=1 -DHAVE_GLINTPTRARB=1 -DHAVE_GLCHAR=1 -DHAVE_GLCHARARB=1 -DHAVE_GLHALFARB=1 -DHAVE_GLINT64EXT=1 -DHAVE_WX_STC_STC_H=1 -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/emulator/beam -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/include -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/include/x86_64-apple-darwin13.4.0 -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/include/internal -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/include/internal/x86_64-apple-darwin13.4.0 -I/private/tmp/erlang-y3rpKH/otp-OTP-17.4/erts/emulator/sys/unix  wxe_impl.cpp -o x86_64-apple-darwin13.4.0/wxe_impl.o
./wxe_impl.h:28:10: fatal error: 'wx/glcanvas.h' file not found
#include <wx/glcanvas.h>
         ^
```
That's very weird, as /opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0 is in the list of includes, and /opt/homebrew/Cellar/wxmac/3.0.2/include/wx-3.0/wx/glcanvas.h exists.

**Comment by jacknagel** [comment]
Can you apply this patch and see if it helps?

```diff
diff --git a/Library/Formula/erlang.rb b/Library/Formula/erlang.rb
index b650516..f427c21 100644
--- a/Library/Formula/erlang.rb
+++ b/Library/Formula/erlang.rb
@@ -71,7 +71,7 @@ def install
     args << "--enable-darwin-64bit" if MacOS.prefer_64_bit?
     args << "--enable-native-libs" if build.with? "native-libs"
     args << "--enable-dirty-schedulers" if build.with? "dirty-schedulers"
-    args << "--enable-wx" if build.with? "wxmac"
+    args << "--with-wx-prefix=#{Formula["wxmac"].opt_prefix}" if build.with? "wxmac"
 
     if MacOS.version >= :snow_leopard and MacOS::CLT.installed?
       args << "--with-dynamic-trace=dtrace"
```

**Comment by grep0** [comment]
@jacknagel No effect: https://gist.github.com/anonymous/9863e3bf55f4b0369162

**Comment by grep0** [comment]
As a temporary workaround, is it possible to build erlang without the linkage to wxmac?

**Comment by jacknagel** [comment]
`brew install erlang --without-wxmac`

**Comment by jacknagel** [comment]
```
HOMEBREW_PREFIX: /Users/mvr
HOMEBREW_CELLAR: /opt/homebrew/Cellar
```

```
superenv removed:  -Werror=return-type -g -Wall -m64 -g -O2 -I/Users/mvr/opt/wxmac/lib/wx/include/osx_cocoa-unicode-3.0 -I/Users/mvr/opt/wxmac/include/wx-3.0
```

The compiler wrapper resolves `/Users/mvr/opt/wxmac/lib/wx/include/osx_cocoa-unicode-3.0` to `/opt/homebrew/Cellar/wxmac/3.0.2/lib/wx/include/osx_cocoa-unicode-3.0`, and paths that begin with `/opt` are stripped unless Homebrew itself is installed in `/opt`.

In this case, only the cellar is in `/opt`, a possibility which was not considered, so it confuses the logic.

**Comment by grep0** [comment]
Works without wxmac, thanks.

I have installed Homebrew in /opt/homebrew and made a symlink from /opt/homebrew/bin/brew to $HOME/bin/brew ($HOME/bin is in my $PATH). Weird enough, now all the instalations go to $HOME, but cellar, library and git all are under /opt/homebrew 
Usually this configuration works, but in the erlang case it failed.

**Comment by jacknagel** [comment]
Yeah, the prefix is relative to the brew executable (without resolving symlinks), but the cellar is located relative to the repository, unless prefix+Cellar exists already:

https://github.com/Homebrew/homebrew/blob/3a02c8b6c30a52309cdafdc011fe2fa724970704/Library/Homebrew/global.rb#L51-66
