### PR TITLE
fix ansible on 10.11 by adding ffi dependency

### LINKED ISSUE #43661: ansible 1.9.3 fails to build on Xcode-only OS X 10.11
Hi,

ansible 1.9.2 was building fine, trying to upgrade to 1.9.3 and the following happens :

```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/ansible/1.9.3/libexec/vendor --single-version-externally-managed --record=installed.txt
c/_cffi_backend.c:13:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^
1 error generated.
error: command 'clang' failed with exit status 1
```

Full gist : https://gist.github.com/anonymous/598cad13d3a36f3e9753

### PR DESCRIPTION
**Pull request by lucas-clemente**
fixes #43661

### CODE REVIEW

**Comment by lucas-clemente** [comment]
I've realized that `ffi.h` is actually present in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/ffi`, but I don't know how to properly handle that. Could somebody else take a look?

**Comment by tdsmith** [comment]
Closing this PR since we want to use the system libffi.
