### ISSUE TITLE
ffmpeg 2.8.3 does not build with libvpx 1.5.0

### ISSUE THREAD

**Issue by dcwar** [Homebrew/homebrew#47029]
Builds fine with libvpx 1.4.0, but will not build with libvpx 1.5.0. The following error is given in configure line 1136:

`libavcodec/libvpxenc.c:107:6: error: use of undeclared identifier 'VP8E_UPD_ENTROPY'
    [VP8E_UPD_ENTROPY]           = "VP8E_UPD_ENTROPY",
     ^`

Ouput of gists-logs: https://gist.github.com/anonymous/ddf00bb2f03b67ee660c

**Comment by yougene** [comment]
same here:

libavcodec/libvpxenc.c:108:6: error: use of undeclared identifier 'VP8E_UPD_REFERENCE'
    [VP8E_UPD_REFERENCE]         = "VP8E_UPD_REFERENCE",
     ^
libavcodec/libvpxenc.c:109:6: error: use of undeclared identifier 'VP8E_USE_REFERENCE'; did you mean 'VP8_SET_REFERENCE'?
    [VP8E_USE_REFERENCE]         = "VP8E_USE_REFERENCE",
     ^~~~~~~~~~~~~~~~~~
     VP8_SET_REFERENCE
/usr/local/Cellar/libvpx/1.5.0/include/vpx/./vp8.h:45:3: note: 'VP8_SET_REFERENCE' declared here
  VP8_SET_REFERENCE           = 1,    /**< pass in an external frame into decoder to be used as reference frame */
  ^
3 errors generated.
CC	libavcodec/libxvid.o
make: *** [libavcodec/libvpxenc.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by gerwinbrunner** [comment]
+1

**Comment by DomT4** [comment]
The joys of having a bundle of optional dependencies in the `ffmpeg` formula. Needs reporting upstream, and if they haven't fixed it already with something we can backport the option will either need to be removed or the old version of `libvpx` vendored privately for the meanwhile.

**Comment by protrolium** [comment]
I am receiving the same error message as @yougene

**Comment by vigo** [comment]
+1

**Comment by yougene** [comment]
Fixed by UniqMartin in Issue #47050 
Thanks!

**Comment by UniqMartin** [comment]
@yougene Thanks for noticing! Somehow I managed to completely miss this issue. For reference, the fix happened in #47054. Closing, as this should be fixed for everyone.
