### ISSUE TITLE
python3 (v 3.5.1) failed to build on 10.7.5-x86_64

### ISSUE THREAD

**Issue by brandonwolfgang** [Homebrew/homebrew#47578]
I initially encountered this issue when running `brew upgrade` with `python3 (v 3.4.3)` already installed, so I then ran `brew uninstall python3` and attempted to reinstall using `brew install python3`. I also deleted all python3 related downloads in `~/Library/Caches/Homebrew/` and any logs in `~/Library/Logs/Homebrew/python3/`.

I've completed all the standard troubleshooting steps like running `brew update` twice and running `brew doctor`, but I consistently receive `Already up-to-date.` and `Your system is ready to brew.`, so I'm fairly sure it's not related to my Homebrew installation.

The specific output of the `brew install python3` command is as follows:
```
Last 15 lines from /Users/brandonwolfgang/Library/Logs/Homebrew/python3/03.make:
cd PythonLauncher && make install DESTDIR=
sed 's/%VERSION%/'"`DYLD_FRAMEWORK_PATH=/private/tmp/python320151231-81784-izricf/Python-3.5.1 ../../python.exe -c 'import platform; print(platform.python_version())'`"'/g' < ./Info.plist.in > Info.plist
gcc-5 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g  -O3 -Wall -Wstrict-prototypes -o FileSettings.o -c ./FileSettings.m
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:120:0,
                 from ./FileSettings.h:9,
                 from ./FileSettings.m:9:
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:75:24: error: expected identifier or '(' before '^' token
 @property (copy) void (^terminationHandler)(NSTask *) NS_AVAILABLE(10_7, NA);
                        ^
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:78:1: error: expected identifier before 'end'
 @end
 ^
make[2]: *** [FileSettings.o] Error 1
make[1]: *** [install_PythonLauncher] Error 2
make: *** [frameworkinstallapps] Error 2
```

I'm at a loss as my other machines (running OS X 10.10) have not encountered this issue.

Here's a [link to the related gist](https://gist.github.com/anonymous/fafcd2d15551ae028369).

Any help is greatly appreciated.

**Comment by tschoonj** [comment]
I think this build failure is triggered because you're using gcc-5 instead of clang. The former appears to be choking on the ObjC syntax.

**Comment by brandonwolfgang** [comment]
Ah that may explain it, I installed `coreutils` so I could use `gsort`. I'm not sure why this installation would default to using `gcc-5` rather than `clang` though. Is there a way to manually force `clang` when installing formulae?

**Comment by mistydemeo** [comment]
The version of clang that comes with your version of Xcode is blacklisted because it's known not to work for building Python 3. Sorry!

**Comment by brandonwolfgang** [comment]
Thanks @mistydemeo! It's odd though because as mentioned in my original post I previously had 3.4.3 installed via homebrew and it worked without issue. This only arose when I ran `brew upgrade` and the 3.5.1 install began. Now I can't (easily) get back to 3.4.3 and 3.5.1 won't install. Any ideas?

**Comment by mistydemeo** [comment]
It looks like that was only added a few days ago, and didn't apply to old versions: 9be7b941

You could try this and let us know if it works:

```
brew install apple-gcc42
brew install python3 --cc=gcc-4.2
```

**Comment by brandonwolfgang** [comment]
I owe you a coffee @mistydemeo, that did it! The only issue I encountered was that `apple-gcc42` is part of `homebrew/dupes` so the proper command is `brew install homebrew/dupes/apple-gcc42`.

**Comment by elotgamu** [comment]
Thanks for the tip I owe you a coffee too, @mistydemeo @brandonwolfgang .... It works like on old OSX 10.7.5
