### ISSUE TITLE
lrdf failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43921]
https://gist.github.com/468a1ebb8d279da4f86b

Failing to find OpenSSL.

```
lrdf.c:10:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make[1]: *** [lrdf.lo] Error 1
```

**Comment by DomT4** [comment]
Closing in favour of #43922.
