### PR TITLE
lrdf: add openssl dependency

### LINKED ISSUE #43921: lrdf failed to build on 10.11
https://gist.github.com/468a1ebb8d279da4f86b

Failing to find OpenSSL.

```
lrdf.c:10:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make[1]: *** [lrdf.lo] Error 1
```

### PR DESCRIPTION
**Pull request by apjanke**
Fixes #43921

### CODE REVIEW

**Comment by DomT4** [comment]
Please bump the revisions when you add new `openssl` dependencies, if it was previously hooking the system. Thanks!

**Comment by DomT4** [comment]
Oh, you did here. Sorry :grin:

**Comment by DomT4** [comment]
Merged in https://github.com/Homebrew/homebrew/commit/bd8d0e64da641a46b1535b5774081fc3f7f3df22. Thank you again @apjanke! :smiley_cat:

**Comment by apjanke** [comment]
You're welcome!
