### ISSUE TITLE
ace failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42255]
https://gist.github.com/aeb1ee7ef5d60d6fc5ae

Doing an installation of all the packages on 10.11. It's failing to find one of its headers.

```
In file included from Name_Request_Reply.cpp:3:
In file included from /private/tmp/ace20150729-48175-1p0k4gy/ACE_wrappers/ace/Name_Request_Reply.h:24:
In file included from /private/tmp/ace20150729-48175-1p0k4gy/ACE_wrappers/ace/Basic_Types.h:42:
In file included from /private/tmp/ace20150729-48175-1p0k4gy/ACE_wrappers/ace/config-lite.h:24:
/private/tmp/ace20150729-48175-1p0k4gy/ACE_wrappers/ace/config-macros.h:24:10: fatal error: 'ace/config.h' file not found
#include "ace/config.h"
         ^
1 error generated.
```

**Comment by qijialiu** [comment]
Same issue. Anyone to help?

**Comment by dunn** [comment]
My guess is they need to explicitly add support for 10.11. The source has headers for each version:
```
🔥  l ace | ag macos
-rw-r--r--   1 cat  admin     368 Aug 27 21:32 config-macosx-iOS-hardware.h
-rw-r--r--   1 cat  admin     282 Aug 27 21:32 config-macosx-iOS-simulator.h
-rw-r--r--   1 cat  admin    6068 Aug 27 21:32 config-macosx-leopard.h
-rw-r--r--   1 cat  admin     911 Aug 27 21:32 config-macosx-lion.h
-rw-r--r--   1 cat  admin     464 Aug 27 21:32 config-macosx-mavericks.h
-rw-r--r--   1 cat  admin     380 Aug 27 21:32 config-macosx-mountainlion.h
-rw-r--r--   1 cat  admin    4876 Aug 27 21:32 config-macosx-panther.h
-rw-r--r--   1 cat  admin     404 Aug 27 21:32 config-macosx-snowleopard.h
-rw-r--r--   1 cat  admin    5571 Aug 27 21:32 config-macosx-tiger.h
-rw-r--r--   1 cat  admin     226 Aug 27 21:32 config-macosx-yosemite.h
-rw-r--r--   1 cat  admin    4744 Aug 27 21:32 config-macosx.h
```
This suggests they're sort of aware of the issue http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=4167 but it would probably help to poke them by opening another issue on their Bugzilla.

**Comment by felixbuenemann** [comment]
I've created PR DOCGroup/ATCD#141 to fix this upstream and PR #43947 to integrate the proposed patch until a new version is released.

**Comment by felixbuenemann** [comment]
@DomT4 I think this issue can be closed.

**Comment by DomT4** [comment]
Done :wink:
