### ISSUE TITLE
gpgme failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42500]
https://gist.github.com/ce25bc1805addf087b37

```
clang -DHAVE_CONFIG_H -I. -I..  -I/usr/local/Cellar/libgpg-error/1.19/include   -I/usr/local/Cellar/libassuan/2.2.1/include -I/usr/local/Cellar/libgpg-error/1.19/include   -g -O2 -Wall -Wcast-align -Wshadow -Wstrict-prototypes -c -o gpgme-tool.o gpgme-tool.c
In file included from gpgme-tool.c:36:
/usr/local/include/argp.h:39:13: error: cannot combine with previous 'int' declaration specifier
typedef int error_t;
            ^
../config.h:258:17: note: expanded from macro 'error_t'
#define error_t int
                ^
1 error generated.
make[2]: *** [gpgme-tool.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
Can no longer reproduce this with latest release & GM Xcode.

```
==> Summary
🍺  /usr/local/Cellar/gpgme/1.6.0: 21 files, 1.8M, built in 3.9 minutes
```

**Comment by apjanke** [comment]
It's still failing with the same error for me on latest release & GM Xcode 7.

https://gist.github.com/b80d74de611ed08d9c7f

This might have been a misdiagnosis about it being 10.11-specific. That included file `/usr/local/include/argp.h` is from `argp-standalone`, which I had installed first. Doing a `brew unlink argp-standalone` was enough to get it to build. Conversely, installing `argp-standalone` on 10.9 will break the gpgme build there, too.

Would it be appropriate to add a conflict to the formula for this?

**Comment by DomT4** [comment]
https://github.com/Homebrew/homebrew/commit/a2ef513e1298eadfeb83920352673b628c273025
