### ISSUE TITLE
php55 failed to build on 10.11.1 (couldn't understand kern.osversion `15.0.0')

### ISSUE THREAD

**Issue by aburakovskiy** [Homebrew/homebrew#45858]
I am trying to install php55:
`brew install php55 --with-apache --with-mysql --with-postgresql --with-intl`
I get the error: *couldn't understand kern.osversion `15.0.0'*
https://gist.github.com/aburakovskiy/889262aad6984f69112d

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-php#2513

**Comment by DomT4** [comment]
Moved this to the PHP tap where the formula is hosted; they'll be able to help you more than us core folks can :).

**Comment by davidcelis** [comment]
I'm not so sure this should be moved, actually. I'm experiencing the same issue while trying to install macvim, so it's definitely not an isolated problem:

```
% brew install macvim --with-override-system-vim --with-lua
==> Downloading https://github.com/macvim-dev/macvim/archive/snapshot-81.tar.gz
Already downloaded: /Library/Caches/Homebrew/macvim-7.4-81.tar.gz
==> ./configure --with-features=huge --enable-multibyte --with-macarchs=x86_64 --enable-perlinterp --enable-rubyinterp --enable-tc
==> make
Last 15 lines from /Users/david/Library/Logs/Homebrew/macvim/02.make:
^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:16:12: note: previous definition is here
@interface NSArray<__covariant ObjectType> : NSObject <NSCopying, NSMutableCopying, NSSecureCoding, NSFastEnumeration>
           ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:32: error: method type specifier must start with '-' or '+'
@interface NSArray<ObjectType> (NSExtendedArray)
                               ^
/System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:26:33: error: expected a type
@interface NSArray<ObjectType> (NSExtendedArray)
                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [objects/os_macosx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [first] Error 2
couldn't understand kern.osversion `15.0.0'

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
macvim: disable ruby integration on 10.6 https://github.com/Homebrew/homebrew/pull/40255
MacVim fails to build (OS X 10.10.3) https://github.com/Homebrew/homebrew/issues/40206
macvim failed to build on 10.6.8 https://github.com/Homebrew/homebrew/issues/38047
```

**Comment by DomT4** [comment]
@davidcelis Most of the time this because:
* Mismatched CLT/Xcode mix
* Xcode or CLT not up-to-date
* The build picks up on an alternative compiler that causes problems (GCC-4.2 is known to do this on occasion).

If none of those are the case for you, please open a new issue.

**Comment by davidcelis** [comment]
I'm updating XCode as we speak; it likely is the issue. For some reason, I'm still on 6.4 instead of 7.1. Somehow I ended up with a version not managed by the App Store.
