### ISSUE TITLE
gsoap failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42502]
https://gist.github.com/d1de8bcc55bd01761f34

```
clang -DHAVE_CONFIG_H -I. -I..       -DMACOSX -Wno-deprecated-declarations -MT libgsoap_a-stdsoap2.o -MD -MP -MF .deps/libgsoap_a-stdsoap2.Tpo -c -o libgsoap_a-stdsoap2.o `test -f 'stdsoap2.c' || echo './'`stdsoap2.c
stdsoap2.c:4874:32: error: use of undeclared identifier 'SOL_TCP'
  if (setsockopt(soap->master, SOL_TCP, TCP_FASTOPEN, (char*)&set, sizeof(int)))
                               ^
1 error generated.
make[1]: *** [libgsoap_a-stdsoap2.o] Error 1
```

**Comment by DomT4** [comment]
Moving to tracking in #40837.
