### PR TITLE
cmake: fix for openssl 1.0.2

### PR DESCRIPTION
**Pull request by DomT4**
Seems pretty much every CMake project that uses SSL is using the same broken Regex code for finding OpenSSL. Welp. Including CMake themselves. Double welp.

This is the upstream patch that will be in the next release, and is in the HEAD already.

### CODE REVIEW

**Comment by DomT4** [comment]
This should also fix the recent build failure in #36081.

**Comment by DomT4** [comment]
The single failure looks unrelated. Looks like a boost failure actually, perhaps the formula involved needs a revision:

```
Testing points2grid
==> /usr/local/Cellar/points2grid/1.3.0/bin/points2grid -i /usr/local/Cellar/points2grid/1.3.0/libexec/example.las -o example --max --output_format grid
dyld: Symbol not found: __ZNK5boost15program_options22error_with_option_name23substitute_placeholdersERKSs
  Referenced from: /usr/local/Cellar/points2grid/1.3.0/bin/points2grid
  Expected in: /usr/local/lib/libboost_program_options-mt.dylib
 in /usr/local/Cellar/points2grid/1.3.0/bin/points2grid
Error: points2grid: failed
Failed executing: /usr/local/Cellar/points2grid/1.3.0/bin/points2grid -i /usr/local/Cellar/points2grid/1.3.0/libexec/example.las -o example --max --output_format grid
```

**Comment by DomT4** [comment]
` points2grid ` builds and tests fine for me on Yosemite, and on the bot. Perhaps that rogue test is just a Mountain Lion quirk. I don't have 10.8 to test sadly.

**Comment by DomT4** [comment]
#36202 should also be fixed once this is merged.

**Comment by mikemcquaid** [comment]
Thanks @DomT4!

**Comment by DomT4** [comment]
Thanks Mike! Apologies for the inlined patch :wink:

**Comment by mikemcquaid** [comment]
No worries @DomT4, appreciate the quick fix.
