### ISSUE TITLE
ffmpeg compile error

### ISSUE THREAD

**Issue by DLaboratory** [Homebrew/homebrew#48965]
```
dlaboratorydeMacBook-Air:~ dlab$ brew install --with-faac --with-fdk-aac --with-fontconfig --with-freetype --with-libass --with-libssh --with-libvorbis --with-libvpx --with-webp --with-rtmpdump --with-opus --with-tools --with-x265 ffmpeg
==> Downloading https://ffmpeg.org/releases/ffmpeg-2.8.6.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/2.8.6 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=gcc-5 
==> make install
Last 15 lines from /Users/dlab/Library/Logs/Homebrew/ffmpeg/02.make:
 static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;
                                        ^
CC	libavcodec/vorbis.o
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CoreVideo.h:25:0,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/VideoToolbox.framework/Headers/VTCompressionSession.h:21,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/VideoToolbox.framework/Headers/VideoToolbox.h:7,
                 from libavcodec/videotoolbox.h:35,
                 from libavcodec/videotoolbox.c:25:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/CoreVideo.framework/Headers/CVDisplayLink.h:152:92: error: unknown type name 'CVDisplayLinkOutputHandler'
 CV_EXPORT CVReturn CVDisplayLinkSetOutputHandler( CVDisplayLinkRef CV_NONNULL displayLink, CVDisplayLinkOutputHandler CV_NONNULL handler );
                                                                                            ^
make: *** [libavcodec/videotoolbox.o] Error 1
make: *** Waiting for unfinished jobs....
CC	libavcodec/vorbis_data.o
CC	libavcodec/vorbis_parser.o

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
ffmpeg --with-faac failed to build on 10.11 https://github.com/Homebrew/homebrew/issues/48824
```

That's weird.

**Comment by mikemcquaid** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Please do

**Comment by DLaboratory** [comment]
1. I have already done `brew update`, `brew upgrade` before installing ffmpeg.
2. `brew doctor` only gave the following information, which seems has nothing to do with ffmpeg.
```
Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:
    gettext
```

**Comment by mistydemeo** [comment]
Please include the full set of logs requested in the troubleshooting list. Thanks!
