### ISSUE TITLE
cputhrottle failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42394]
https://gist.github.com/5349c9c1883795c1394a

On 10.11 PB3.

```
/usr/bin/g++ -c -g -Wall -I..///boost_1_43_0 cputhrottle.cc
In file included from cputhrottle.cc:5:
./manip.h:4:10: fatal error: 'boost/shared_ptr.hpp' file not found
#include <boost/shared_ptr.hpp>
         ^
1 error generated.
make: *** [cputhrottle.o] Error 1
```

**Comment by dunn** [comment]
It also explodes if you try to override the make variables with what should be the correct ones:
```ruby
  def install
    system "make", "all", "CC=#{ENV.cc}",
           "BOOST_INCLUDES=#{Formula["boost"].opt_include}",
           "BOOST_LIBS=#{Formula["boost"].opt_lib}"
    bin.install "cputhrottle"
  end
```
https://gist.github.com/bf25dee9820fc97080c7

**Comment by DomT4** [comment]
Moving to tracking in #40837. If you report this one upstream let us know in that thread and I'll add a link to that report, Thanks!
