### ISSUE TITLE
pygobject failed to build on 10.10.1

### ISSUE THREAD

**Issue by anthony-ng** [Homebrew/homebrew#36207]
CC _gi_la-pygboxed.lo
In file included from pygi-error.h:26,
from gobjectmodule.c:40:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
In file included from pygi.h:30,
from pygboxed.c:29:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
make[2]: *** [_gi_la-pygboxed.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [_gi_la-gobjectmodule.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**Comment by jacknagel** [comment]
http://git.io/brew-troubleshooting

**Comment by uwehermann** [comment]
Hi, I'm getting pretty much the same errors when trying to build pygobject3 (on 10.6.8 in my case), see https://github.com/Homebrew/homebrew/issues/34734.

My logs (from that issue):
https://gist.github.com/anonymous/9df19cb5aeddebea3560
