### ISSUE TITLE
dwarf failed to build on 10.11, 10.10, 10.9

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42479]
https://gist.github.com/5675f097b199ff414a4a

Failing with a type definition error, even though Homebrew `gcc` is installed.

```
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-lex.cfgyy.o `test -f 'lex.cfgyy.c' || echo './'`lex.cfgyy.c
In file included from lex.cfgyy.c:61:0:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/inttypes.h:235:8: error: unknown type name 'intmax_t'
 extern intmax_t
```

**Comment by larseggert** [comment]
Same issue on 10.10.4:
```
==> Verifying dwarf-0.3.0.tar.gz checksum
tar xf /Library/Caches/Homebrew/dwarf-0.3.0.tar.gz
==> ./configure --prefix=/usr/local/Cellar/dwarf/0.3.0 --disable-dependency-tracking
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc-5
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc-5 accepts -g... yes
checking for gcc-5 option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc-5... none
checking whether make sets $(MAKE)... (cached) yes
checking how to run the C preprocessor... gcc-5 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -ll
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for ranlib... ranlib
checking whether gcc-5 and cc understand -c and -o together... yes
checking for mremap... no
checking for mmap... yes
checking for munmap... yes
checking for malloc... yes
checking for open... yes
checking for lseek... yes
checking for fopen... yes
checking for fclose... yes
checking for getopt... yes
checking for getopt_long... yes
checking for ftruncate... yes
checking for strlen... yes
checking for strdup... yes
checking for free... yes
checking for strcmp... yes
checking for isalnum... yes
checking for isdigit... yes
checking for mremap... (cached) no
checking for main in -lreadline... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/cmdline/Makefile
config.status: creating src/libdwarf/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
==> make install
Making install in src
Making install in libdwarf
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-am
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-y.tab.o `test -f 'y.tab.c' || echo './'`y.tab.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-lex.cfgyy.o `test -f 'lex.cfgyy.c' || echo './'`lex.cfgyy.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-vars.o `test -f 'vars.c' || echo './'`vars.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-utils.o `test -f 'utils.c' || echo './'`utils.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-libdwarf.o `test -f 'libdwarf.c' || echo './'`libdwarf.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-dw_switchers.o `test -f 'dw_switchers.c' || echo './'`dw_switchers.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-dw_elf_utils.o `test -f 'dw_elf_utils.c' || echo './'`dw_elf_utils.c
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-dw_macho_utils.o `test -f 'dw_macho_utils.c' || echo './'`dw_macho_utils.c
In file included from lex.cfgyy.c:61:0:
/usr/include/inttypes.h:235:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:236:9: error: unknown type name 'intmax_t'
 imaxabs(intmax_t j);
         ^
/usr/include/inttypes.h:240:2: error: unknown type name 'intmax_t'
  intmax_t quot;
  ^
/usr/include/inttypes.h:241:2: error: unknown type name 'intmax_t'
  intmax_t rem;
  ^
/usr/include/inttypes.h:246:9: error: unknown type name 'intmax_t'
 imaxdiv(intmax_t __numer, intmax_t __denom);
         ^
/usr/include/inttypes.h:246:27: error: unknown type name 'intmax_t'
 imaxdiv(intmax_t __numer, intmax_t __denom);
                           ^
/usr/include/inttypes.h:250:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:256:8: error: unknown type name 'uintmax_t'
 extern uintmax_t
        ^
/usr/include/inttypes.h:263:8: error: unknown type name 'intmax_t'
 extern intmax_t
        ^
/usr/include/inttypes.h:269:8: error: unknown type name 'uintmax_t'
 extern uintmax_t
        ^
make[3]: *** [libdwarf_a-lex.cfgyy.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make install
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
```

**Comment by apjanke** [comment]
And on 10.9.5, with CLT installed. Looks like this isn't 10.11-specific at all.

https://gist.github.com/cb563c2353c3b7bd6476
