### ISSUE TITLE
libpeas failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42685]
https://gist.github.com/9821de3941424b4a0153

Can't find OpenSSL. Works on 10.9 with or without CLT.

```
Making install in lib
/bin/sh ../libtool --tag=CXX   --mode=compile clang++ -DHAVE_CONFIG_H -I.. -I../include/ -I../include/      -DNDEBUG   -g -O2 -c -o params.lo params.cc
libtool: compile:  clang++ -DHAVE_CONFIG_H -I.. -I../include/ -I../include/ -DNDEBUG -g -O2 -c params.cc  -fno-common -DPIC -o .libs/params.o
params.cc:4:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^
1 error generated.
make[1]: *** [params.lo] Error 1
```

**Comment by DomT4** [comment]
The snippet above here seems to be something else? There's no OpenSSL linkage in `libpeas`?

**Comment by apjanke** [comment]
Oops! Think that was from `libopkele`. Fixed with the snippets from `libpeas` failed build. Sorry.

**Comment by DomT4** [comment]
Moving to tracking in #40837. Same gig here about reporting upstream and letting us know so we can put a link in the formula, etc.
