### ISSUE TITLE
csup failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42396]
https://gist.github.com/b5cd69cb64d02eeeaf8d

On OS X 10.11 PB3.

```
clang -DNDEBUG -DHAVE_FFLAGS -O -pipe -I/usr/local/include -Wall -W -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch -Wshadow -Wcast-align -Wunused-parameter -Wchar-subscripts -Winline -Wnested-externs -Wredundant-decls -Wno-format-y2k -c -o attrstack.o attrstack.c
In file included from attrstack.c:32:
./misc.h:38:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make: *** [attrstack.o] Error 1
```
