### ISSUE TITLE
gmediaserver fails to build on 10.8+

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41269]
I installed *all* formulae from the core, this is one of the issues I ran into. I’m at work, will check tonight.

```
$ brew install gmediaserver
==> Installing gmediaserver dependency: libupnp
==> Downloading https://homebrew.bintray.com/bottles/libupnp-1.6.19.yosemite.bottle.1.tar.gz
######################################################################## 100,0%
==> Pouring libupnp-1.6.19.yosemite.bottle.1.tar.gz
🍺  /usr/local/Cellar/libupnp/1.6.19: 32 files, 1,0M
==> Installing gmediaserver
==> Downloading http://download.savannah.gnu.org/releases/gmediaserver/gmediaserver-0.13.0.tar.gz
==> Downloading from http://mirror6.layerjet.com/nongnu//gmediaserver/gmediaserver-0.13.0.tar.gz
######################################################################## 100,0%
==> Patching
patching file src/metadata.c
patching file src/main.c
==> ./configure --prefix=/usr/local/Cellar/gmediaserver/0.13.0
==> make
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
```

Logs: https://gist.github.com/caa35695bf2970c14db1

**Comment by bfontaine** [comment]
```
clang -DHAVE_CONFIG_H -I. -I. -I..  -I../lib -I../lib   -Wall -I.. -D_THREAD_SAFE -I/usr/local/Cellar/libupnp/1.6.19/include/upnp   -g -O2 -c upnp.c
upnp.c:268:47: error: passing 'struct sockaddr_storage' to parameter of incompatible type 'struct in_addr'
    say(3, _("Event source: %s\n"), inet_ntoa(request->CtrlPtIPAddr));
                                              ^~~~~~~~~~~~~~~~~~~~~
/usr/include/arpa/inet.h:76:32: note: passing argument to parameter here
char            *inet_ntoa(struct in_addr);
                                         ^
upnp.c:309:47: error: passing 'struct sockaddr_storage' to parameter of incompatible type 'struct in_addr'
    say(3, _("Event source: %s\n"), inet_ntoa(request->CtrlPtIPAddr));
                                              ^~~~~~~~~~~~~~~~~~~~~
/usr/include/arpa/inet.h:76:32: note: passing argument to parameter here
char            *inet_ntoa(struct in_addr);
                                         ^
2 errors generated.
```

**Comment by apjanke** [comment]
Same error on 10.11 Public Beta.

**Comment by bfontaine** [comment]
Same error on 10.11.2.

**Comment by ilovezfs** [comment]
Same error on 10.8, so the title should probably be revised since this apparently has nothing to do with >=10.10
```
==> Installing gmediaserver
==> Downloading http://download.savannah.gnu.org/releases/gmediaserver/gmediaserver-0.13.0.tar.gz
==> Downloading from http://gnu.mirrors.pair.com/savannah/savannah//gmediaserver/gmediaserver-0.13.0.
######################################################################## 100.0%
==> Patching
patching file src/metadata.c
patching file src/main.c
==> ./configure --prefix=/usr/local/Cellar/gmediaserver/0.13.0
==> make
Last 15 lines from /Users/joe/Library/Logs/Homebrew/gmediaserver/02.make:
                                         ^
upnp.c:309:47: error: passing 'struct sockaddr_storage' to parameter of incompatible type 'struct in_addr'
    say(3, _("Event source: %s\n"), inet_ntoa(request->CtrlPtIPAddr));
                                              ^~~~~~~~~~~~~~~~~~~~~
/usr/include/arpa/inet.h:98:32: note: passing argument to parameter here
char            *inet_ntoa(struct in_addr);
                                         ^
2 errors generated.
clang -DHAVE_CONFIG_H -I. -I. -I..  -I../lib -I../lib   -Wall -I.. -D_THREAD_SAFE -I/usr/local/Cellar/libupnp/1.6.19/include/upnp  -g -O2 -c webserver.c
make[4]: *** [upnp.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
gmediaserver fails to build on 10.10+ https://github.com/Homebrew/homebrew/issues/41269
Josephs-MacBook-Pro:~ joe$
```

**Comment by bfontaine** [comment]
Thanks @ilovezfs; I changed the title.

**Comment by ilovezfs** [comment]
@bfontaine You're welcome. Also looks like it built successfully against libupnp 1.6.6, but not 1.6.18 or 1.6.19, so I wonder if either 1.6.6, or whatever the greatest version is it can build against is, should be vendored in to fix it? Or at least diffing 1.6.6 against 1.6.18 should reveal the problem if you'd prefer a real fix.
```
Josephs-MacBook-Pro:local joe$ brew install libupnp
==> Downloading http://downloads.sourceforge.net/project/pupnp/pupnp/libUPnP%201.6.6/libupnp-1.6.6.ta
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libupnp/1.6.6
==> make install
🍺  /usr/local/Cellar/libupnp/1.6.6: 25 files, 952K, built in 26 seconds
Josephs-MacBook-Pro:local joe$ git reset --hard @{10.minutes.ago}
HEAD is now at 842ef65 Merge remote-tracking branch 'origin/master'
Josephs-MacBook-Pro:local joe$ brew edit libupnp
Josephs-MacBook-Pro:local joe$ brew install gmediaserver
==> Downloading http://download.savannah.gnu.org/releases/gmediaserver/gmediaserver-0.13.0.tar.gz
Already downloaded: /Users/joe/Library/Caches/Homebrew/gmediaserver-0.13.0.tar.gz
==> Patching
patching file src/metadata.c
patching file src/main.c
==> ./configure --prefix=/usr/local/Cellar/gmediaserver/0.13.0
==> make
==> make install
🍺  /usr/local/Cellar/gmediaserver/0.13.0: 10 files, 303.8K, built in 31 seconds
Josephs-MacBook-Pro:local joe$ 
```

**Comment by MrDuncanM** [comment]
The following path fixes the compilation issues.

`diff --git a/src/contentdir.c b/src/contentdir.c
index e1e7547..efbad5d 100644
--- a/src/contentdir.c
+++ b/src/contentdir.c
@@ -18,6 +18,7 @@
  *
  */
 
+#include <assert.h>
 #include <config.h>
 #include <stdint.h>		/* Gnulib/C99 */
 #include <inttypes.h>		/* ? */
 
diff --git a/src/upnp.c b/src/upnp.c
index 19aba6a..cf32e4c 100644
--- a/src/upnp.c
+++ b/src/upnp.c
@@ -265,7 +265,7 @@ handle_get_var_request(struct Upnp_State_Var_Request *request)
     say(3, _("Event device UDN: %s\n"), quotearg(request->DevUDN));
     say(3, _("Event service ID: %s\n"), quotearg(request->ServiceID));
     say(3, _("Event variable name: %s\n"), quotearg(request->StateVarName));
-    say(3, _("Event source: %s\n"), inet_ntoa(request->CtrlPtIPAddr));
+    say(3, _("Event source: %s\n"), inet_ntoa(((struct sockaddr_in *)&request->CtrlPtIPAddr)->sin_addr));
 
     if (strcmp(request->DevUDN, device_udn) != 0) {
         say(1, _("Discarding event - event device UDN (%s) not recognized\n"), quotearg(request->DevUDN));
@@ -306,7 +306,7 @@ handle_action_request(struct Upnp_Action_Request *request)
     say(3, _("Event device UDN: %s\n"), quotearg(request->DevUDN));
     say(3, _("Event service ID: %s\n"), quotearg(request->ServiceID));
     say(3, _("Event action name: %s\n"), quotearg(request->ActionName));
-    say(3, _("Event source: %s\n"), inet_ntoa(request->CtrlPtIPAddr));
+    say(3, _("Event source: %s\n"), inet_ntoa(((struct sockaddr_in *)&request->CtrlPtIPAddr)->sin_addr));
     say_document(4, _("Event action request:\n"), request->ActionRequest);
 
     if (strcmp(request->DevUDN, device_udn) != 0) {
`

**Comment by ilovezfs** [comment]
@MrDuncanM then please open a pull request.
