### ISSUE TITLE
pev failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43936]
https://gist.github.com/3fa1469b9deb807a7814

```
pehash.c:23:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[1]: *** [pehash] Error 1
```

**Comment by DomT4** [comment]
Closing in favour of #43937.

(If you include `Closes #123456` in your commit message it'll happen automatically on merge. Including it in PR summaries doesn't, sadly :cry:)

**Comment by apjanke** [comment]
Oooh. I didn't know it worked in commits. I'm just used to the GH workflow where PRs are merged on the GitHub side.

I'll switch to putting it in commits where applicable.
