### ISSUE TITLE
zorba failed to build on 10.11 w/o CLT

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42372]
Failed on OS X 10.11 Public Beta 3, no CLT. Complaining about missing `zend.h`

https://gist.github.com/2144b9ef5e80fe9c5a02

```
cd /tmp/zorba20150801-5667-q2vcq/zorba-3.0/build/swig/php && /usr/local/Library/ENV/4.3/clang++   -Dzorba_api_php_EXPORTS -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fPIC -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -I/usr/local/opt/icu4c/include -I/usr/local/include -I/tmp/zorba20150801-5667-q2vcq/zorba-3.0/build/include -I/tmp/zorba20150801-5667-q2vcq/zorba-3.0/include -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib    -o CMakeFiles/zorba_api_php.dir/zorba_apiPHP5_wrap.cxx.o -c /tmp/zorba20150801-5667-q2vcq/zorba-3.0/build/swig/php/zorba_apiPHP5_wrap.cxx
/tmp/zorba20150801-5667-q2vcq/zorba-3.0/build/swig/php/zorba_apiPHP5_wrap.cxx:761:10: fatal error: 'zend.h' file not found
#include "zend.h"
         ^
1 error generated.
make[2]: *** [swig/php/CMakeFiles/zorba_api_php.dir/zorba_apiPHP5_wrap.cxx.o] Error 1
make[1]: *** [swig/php/CMakeFiles/zorba_api_php.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
It's a PHP header. Apple may have removed it as part of their header cull, It usually lives in `usr/include/php/Zend/`. It's also possible the lack of CLT is causing some issues. I'll try building it later on my 10.11 VM.

**Comment by lostinplace** [comment]
bump?

**Comment by bfontaine** [comment]
It builds fine on OS X 10.11 with CLT.

**Comment by doersino** [comment]
@bfontaine, have you updated to XCode 7.1, which comes with clang-700.1.76? It doesn't build on my 10.11 machine with the most recent XCode/CLT version:

<img width="377" alt="screen shot 2015-10-23 at 11 54 09" src="https://cloud.githubusercontent.com/assets/1944410/10689644/1779d6ec-797d-11e5-95a4-6a797216813e.png">

```
$ brew install zorba
==> Downloading https://github.com/28msec/zorba/archive/3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/zorba-3.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL
==> make install
Last 15 lines from /Users/noah/Library/Logs/Homebrew/zorba/02.make:
[ 97%] Building CXX object test/unit/CMakeFiles/UnitTests.dir/xmldatamanager.cpp.o
cd /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/unit && /usr/local/Library/ENV/4.3/clang++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/src -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -I/usr/local/opt/icu4c/include -I/usr/local/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/driver -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/driver    -o CMakeFiles/UnitTests.dir/xmldatamanager.cpp.o -c /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/unit/xmldatamanager.cpp
[ 97%] Building CXX object test/unit/CMakeFiles/UnitTests.dir/staticcollectionmanager.cpp.o
cd /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/unit && /usr/local/Library/ENV/4.3/clang++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/src -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -I/usr/local/opt/icu4c/include -I/usr/local/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/driver -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/driver    -o CMakeFiles/UnitTests.dir/staticcollectionmanager.cpp.o -c /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/unit/staticcollectionmanager.cpp
[ 97%] Building CXX object test/unit/CMakeFiles/UnitTests.dir/test_static_context.cpp.o
cd /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/unit && /usr/local/Library/ENV/4.3/clang++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/src -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/src -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -I/usr/local/opt/icu4c/include -I/usr/local/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/include -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/driver -I/tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/driver    -o CMakeFiles/UnitTests.dir/test_static_context.cpp.o -c /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/test/unit/test_static_context.cpp
[ 97%] Linking CXX executable UnitTests
cd /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/test/unit && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/UnitTests.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/UnitTests.dir/UnitTests.cpp.o CMakeFiles/UnitTests.dir/multiple_runs.cpp.o CMakeFiles/UnitTests.dir/plan_serializer.cpp.o CMakeFiles/UnitTests.dir/call_stack.cpp.o CMakeFiles/UnitTests.dir/cxx_api_changes.cpp.o CMakeFiles/UnitTests.dir/external_function.cpp.o CMakeFiles/UnitTests.dir/no_folding.cpp.o CMakeFiles/UnitTests.dir/ordpath_big.cpp.o CMakeFiles/UnitTests.dir/uri_file_decoding_test.cpp.o CMakeFiles/UnitTests.dir/ext_in_opt.cpp.o CMakeFiles/UnitTests.dir/collection.cpp.o CMakeFiles/UnitTests.dir/test_audit.cpp.o CMakeFiles/UnitTests.dir/streamable_string.cpp.o CMakeFiles/UnitTests.dir/main_sequential.cpp.o CMakeFiles/UnitTests.dir/context_item.cpp.o CMakeFiles/UnitTests.dir/datetime.cpp.o CMakeFiles/UnitTests.dir/invoke.cpp.o CMakeFiles/UnitTests.dir/xquery_functions.cpp.o CMakeFiles/UnitTests.dir/xmldatamanager.cpp.o CMakeFiles/UnitTests.dir/staticcollectionmanager.cpp.o CMakeFiles/UnitTests.dir/test_static_context.cpp.o  -o UnitTests  ../../src/libzorba_simplestore.3.0.0.dylib -lpthread /usr/local/opt/icu4c/lib/libicuuc.dylib /usr/local/opt/icu4c/lib/libicui18n.dylib /usr/local/opt/icu4c/lib/libicudata.dylib /usr/lib/libxml2.dylib /usr/local/lib/libxerces-c.dylib /usr/lib/libxml2.dylib /usr/local/lib/libxerces-c.dylib 
[ 97%] Built target UnitTests
[ 97%] Linking CXX shared module _zorba_api_python.so
cd /tmp/zorba20151023-24854-1rxl55a/zorba-3.0/build/swig/python && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/_zorba_api_python.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -bundle -Wl,-headerpad_max_install_names  -o _zorba_api_python.so CMakeFiles/_zorba_api_python.dir/zorba_apiPYTHON_wrap.cxx.o ../../src/libzorba_simplestore.3.0.0.dylib /usr/lib/libpython2.7.dylib -lpthread /usr/local/opt/icu4c/lib/libicuuc.dylib /usr/local/opt/icu4c/lib/libicui18n.dylib /usr/local/opt/icu4c/lib/libicudata.dylib /usr/lib/libxml2.dylib /usr/local/lib/libxerces-c.dylib /usr/lib/libxml2.dylib /usr/local/lib/libxerces-c.dylib 
[ 97%] Built target _zorba_api_python
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
zorba failed to build on 10.11 https://github.com/Homebrew/homebrew/issues/42372

```

**Comment by bfontaine** [comment]
@doersino Nope:
```
$ clang --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by DomT4** [comment]
No problems here:

```
OS X: 10.11.1-x86_64
Xcode: 7.1
CLT: 7.1.0.0.1.1444952191

==> Summary
🍺  /usr/local/Cellar/zorba/3.0_1: 364 files, 37M, built in 10.5 minutes
```

Can you `brew gist-logs` the formula @doersino? Thanks.

**Comment by doersino** [comment]
Sure: https://gist.github.com/anonymous/dab2d50bbb1a3d5fd231

**Comment by apjanke** [comment]
It looks like you have the CLT selected, but not installed. Makes sense; it's doing `-I/usr/include/php/Zend` to pick up the `zend.h` header. It's present on my system where CLT have been installed.

From https://gist.githubusercontent.com/anonymous/dab2d50bbb1a3d5fd231/raw/91c7f522d192f0fd7a11de7a3cc996ec50b601b3/config.out:

```
OS X: 10.11.1-x86_64
Xcode: 7.1
CLT: N/A
```

As a workaround, install the CLT by doing `xcode-select --install`.

This can probably be re-labeled as a "no-CLT" bug.

**Comment by apjanke** [comment]
Yeah, it's CLT, not 10.11-specific. I can reproduce the same error on my no-CLT 10.9.5 box. Re-tagging.
