### ISSUE TITLE
valgrind fails to build on OSX 10.10.1

### ISSUE THREAD

**Issue by jenga** [Homebrew/homebrew#38555]
I am trying to build valgrind in Yosemite using 

```brew install --HEAD valgrind```

And the build is failing due to a 32bit/64 bit memory addressing error. 
Gist is here: https://gist.github.com/5f3edee5466106fcd635

I have also tried compiling valgrind from their trunk repo at svn://svn.valgrind.org/valgrind/trunk and, after changing the configure script to accept my version of the gcc compiler (applellvm-6.1.0), it will fail with the error:

m_initimg/initimg-darwin.c:511:21: error: conflicting types for 'vgPlain_ii_create_image'

Any help would be appreciated.

**Comment by kahnjw** [comment]
Happening here too.

**Comment by jacknagel** [comment]
Can you try upgrading to 10.10.3? I'm not sure Xcode 3 and 10.10.1 will mix well.

If that doesn't help, please report this to the valgrind developers.

**Comment by Sumenia** [comment]
i'm on 10.10.3 and same problem

**Comment by jacknagel** [comment]
It will need to be reported upstream, then. We can't support HEAD builds.
