### ISSUE TITLE
pincaster failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43939]
https://gist.github.com/8954bb7bd8c4b3c1ea66

Can't find OpenSSL.

But even after I add `depends_on "openssl"` [here](https://github.com/apjanke/homebrew/tree/pincaster-openssl-dep), it errors out during the installation phase with a failure to find YAJL headers.

```
clang -DHAVE_CONFIG_H -I. -I..   -Ilevent2 -Ilevent2/include  -D_XPG4_2=1 -I/usr/local/include  -I/usr/include/yajl -g -O2 -pthread -MT app.o -MD -MP -MF .deps/app.Tpo -c -o app.o app.c
clang -DHAVE_CONFIG_H -I. -I..   -Ilevent2 -Ilevent2/include  -D_XPG4_2=1 -I/usr/local/include  -I/usr/include/yajl -g -O2 -pthread -MT parser.o -MD -MP -MF .deps/parser.Tpo -c -o parser.o parser.c
clang -DHAVE_CONFIG_H -I. -I..   -Ilevent2 -Ilevent2/include  -D_XPG4_2=1 -I/usr/local/include  -I/usr/include/yajl -g -O2 -pthread -MT app_config.o -MD -MP -MF .deps/app_config.Tpo -c -o app_config.o app_config.c
clang -DHAVE_CONFIG_H -I. -I..   -Ilevent2 -Ilevent2/include  -D_XPG4_2=1 -I/usr/local/include  -I/usr/include/yajl -g -O2 -pthread -MT utils.o -MD -MP -MF .deps/utils.Tpo -c -o utils.o utils.c
In file included from app_config.c:2:
./common.h:37:10: fatal error: 'yajl_parse.h' file not found
#include <yajl_parse.h>
         ^
In file included from parser.c:2:
./common.h:37:10: fatal error: 'yajl_parse.h' file not found
#include <yajl_parse.h>
         ^
In file included from app.c:4:
./common.h:37:10: fatal error: 'yajl_parse.h' file not found
#include <yajl_parse.h>
         ^
In file included from utils.c:2:
./common.h:37:10: fatal error: 'yajl_parse.h' file not found
#include <yajl_parse.h>
         ^
1 error generated.
```

Adding `depends_on "yajl"` doesn't fix this. It's looking for them in `/usr/include/yajl` instead of `/usr/local/include/yajl` or another Homebrew-controlled location.
