### PR TITLE
pygobject3: avoid redefining structs

### LINKED ISSUE #34734: pygobject3 failed to build on 10.6.8
```
 CC _gi_la-pygboxed.lo
In file included from pygi-error.h:26,
from gobjectmodule.c:40:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
In file included from pygi.h:30,
from pygboxed.c:29:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
make[2]: *** [_gi_la-pygboxed.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [_gi_la-gobjectmodule.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

Full log: https://gist.github.com/anonymous/9df19cb5aeddebea3560

### LINKED ISSUE #36207: pygobject failed to build on 10.10.1
CC _gi_la-pygboxed.lo
In file included from pygi-error.h:26,
from gobjectmodule.c:40:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
In file included from pygi.h:30,
from pygboxed.c:29:
pygi-cache.h:210: error: redefinition of typedef 'PyGIFunctionCache'
pygi-cache.h:34: error: previous declaration of 'PyGIFunctionCache' was here
pygi-cache.h:216: error: redefinition of typedef 'PyGIVFuncCache'
pygi-cache.h:35: error: previous declaration of 'PyGIVFuncCache' was here
make[2]: *** [_gi_la-pygboxed.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [_gi_la-gobjectmodule.lo] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

### PR DESCRIPTION
**Pull request by tdsmith**
Applies upstream commit to avoid compile error (with gcc?).

Fixes #34734. Fixes #36207.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:

**Comment by bfontaine** [comment]
The build failed on the audit part because the homepage should use `https://`.
