### ISSUE TITLE
binwalk failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#43908]
https://gist.github.com/c62c4135b0acd327a417

Fails to find `Python.h`.

```
compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -c'
clang: _configtest.c
_configtest.c:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
_configtest.c:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
failure.
```

Doesn't appear 10-11-specific. I'm getting the same error on 10.9.5.

**Comment by fonnesbeck** [comment]
I get the same behavior for a variety of Python packages after installing Python3 from Homebrew.

**Comment by daveio** [comment]
Also seeing this issue. Happens with and without the --HEAD flag to binwalk.

**Comment by daveio** [comment]
My build output looks very similar to the one posted by @apjanke - here's the full output of `brew install binwalk --with-matplotlib --verbose`: https://gist.github.com/daveio/48bf9dd016145452de7f

**Comment by Drewshg312** [comment]
Experiencing same issue :(
