### ISSUE TITLE
php failed to build on 10.11

### ISSUE THREAD

**Issue by yekz** [Homebrew/homebrew#42197]
```
brew install php56
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php56 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.6.11.tar.bz2/from/this/mirror
Already downloaded: /Library/Caches/Homebrew/php56-5.6.11
==> ./configure --prefix=/usr/local/Cellar/php56/5.6.11_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc
==> make
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```

**Comment by yekz** [comment]
php55：
-----
brew install php55
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing php55 from homebrew/homebrew-php
==> Downloading https://php.net/get/php-5.5.27.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.5.27.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php55/5.5.27_2 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc
==> make
make: *** Waiting for unfinished jobs....
make: *** [sapi/fpm/php-fpm] Error 1
make: *** [sapi/cli/php] Error 1
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.bundle] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

**Comment by bfontaine** [comment]
This issue was moved to Homebrew/homebrew-php#1941
