### ISSUE TITLE
ncmpcpp --HEAD failed to build on 10.10.1

### ISSUE THREAD

**Issue by penetrance** [Homebrew/homebrew#35977]
https://gist.github.com/anonymous/ed30abf49c03ed659832

error in make:
1 error generated.
make[1]: *** [wide_string.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

**Comment by DomT4** [comment]
Blows up here on 10.10.2 as well. Looks like a Boost failure though, or at least, an incompatibility with the newest Boost update:

```
In file included from /usr/local/include/boost/locale/encoding_utf.hpp:12:
/usr/local/include/boost/locale/encoding_errors.hpp:44:51: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
                invalid_charset_error(std::string charset) :
                                                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:188:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
1 error generated.
make[1]: *** [wide_string.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1
```

**Comment by jacknagel** [comment]
Closing since we don't generally don't provide support for HEAD builds for reasons like this. The best option is to work with upstream to resolve the issue before it makes it into an actual release.
