### ISSUE TITLE
fibjs failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#42490]
https://gist.github.com/2dfdf63803a0d0ec96ba

On OS X 10.11 PB4, no CLT.

```
[ 50%] Building C object CMakeFiles/ev.dir/src/ev.c.o
/tmp/fibjs20150803-5267-1tdwqgj/vender/ev/src/ev.c:970:42: error: '_Noreturn' keyword must precede function declarator
  ecb_inline void ecb_unreachable (void) ecb_noreturn;
                                         ^~~~~~~~~~~~
  _Noreturn 
/tmp/fibjs20150803-5267-1tdwqgj/vender/ev/src/ev.c:773:26: note: expanded from macro 'ecb_noreturn'
  #define ecb_noreturn   _Noreturn
                         ^
1 error generated.
make[2]: *** [CMakeFiles/ev.dir/src/ev.c.o] Error 1
make[1]: *** [CMakeFiles/ev.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by DomT4** [comment]
https://github.com/xicilion/fibjs/issues/96

**Comment by xicilion** [comment]
fixed

**Comment by DomT4** [comment]
Closing in favour of #44024.

Thank you for the fix & updating the Homebrew package @xicilion! Really appreciate that.
