### PR TITLE
dwarf: needs gcc-4.9 to compile

### LINKED ISSUE #42479: dwarf failed to build on 10.11, 10.10, 10.9
https://gist.github.com/5675f097b199ff414a4a

Failing with a type definition error, even though Homebrew `gcc` is installed.

```
gcc-5 -DHAVE_CONFIG_H -I. -I../..    -O0 -lm -g -O2 -c -o libdwarf_a-lex.cfgyy.o `test -f 'lex.cfgyy.c' || echo './'`lex.cfgyy.c
In file included from lex.cfgyy.c:61:0:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/inttypes.h:235:8: error: unknown type name 'intmax_t'
 extern intmax_t
```

### PR DESCRIPTION
**Pull request by DomT4**
Reported upstream: https://github.com/elboza/dwarf-ng/issues/1

Closes #42479.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1:
