### ISSUE TITLE
brew install devil not working on os x mavericks

### ISSUE THREAD

**Issue by mcheema** [Homebrew/homebrew#40442]
I am having trouble getting brew install devil to work.
https://gist.github.com/90ae6ca4f96dfa54c214

**Comment by mistydemeo** [comment]
The error:

```
libtool: compile:  gcc-5 -DHAVE_CONFIG_H -I. -I../include/IL -I ./../src-IL/include -I ./../include -std=gnu99 -fgnu89-inline -msse -msse2 -msse3 -g -O2 -c ./../src-IL/src/il_bits.c -o libIL_la-il_bits.o >/dev/null 2>&1
In file included from ./../src-IL/src/il_exr.cpp:14:0:
./../src-IL/include/il_internal.h:230:54: error: expected ',' or '...' before 'FileName'
 ILboolean ilIsValidBmp(ILconst_string CONST_RESTRICT FileName);
                                                      ^
make[1]: *** [libIL_la-il_exr.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by mistydemeo** [comment]
I can reproduce, using GCC 5.1. It works with GCC 4.9.

At a glance this seems to be similar to the [ncurses bug](https://github.com/Homebrew/homebrew-dupes/pull/470) with GCC 5, which was [reported and closed as invalid to the GCC developers](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61832). This should be reported to the Devil developers, though the project seems inactive.

**Comment by mistydemeo** [comment]
Marked as failing with GCC 5; you can `brew install gcc49`, and you should then be able to `brew install devil`.

**Comment by mcheema** [comment]
thanks it builds correctly now

**Comment by ilovezfs** [comment]
The devil formula now builds with GCC 5 thanks to a patch from NetBSD:
https://github.com/Homebrew/homebrew-core/pull/839
https://github.com/Homebrew/homebrew-core/commit/7caa5c9320579d998e521b202fbbf2e2e299e90f
