### ISSUE TITLE
uwsgi failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44018]
https://gist.github.com/958d206bd0c643dbf8fe

```

python
uwsgiconfig.py
--build
brew

core/socket.c:713:28: error: use of undeclared identifier 'SOL_TCP'
                if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                                         ^
1 error generated.

```

**Comment by brooneysn** [comment]
I got this to work in 10.11 by installing the command line tools for 10.10 - Newest version.

**Comment by bartTC** [comment]
Thank you @brooneysn this made it working. I downloaded the latest, stable command line tools from the [developer site](https://developer.apple.com/downloads/).

    "Command Line Tools OS X 10.10 for Xcode 7"	"Sep 16, 2015"

**Comment by toabi** [comment]
Manual "reinstall" of command line tools also fixed this for me.

**Comment by alexanderfrey** [comment]
does not work for me. I'm on capitan, reinstalled xcode-select --install   and still brew install uwsgi does not work. Any recommendations ? Best

**Comment by brooneysn** [comment]
It worked by installing the command line tools:

​

**Comment by apjanke** [comment]
Does anyone know what exactly happens when you install the "Command Line Tools OS X 10.10 for Xcode 7" on a 10.11 system? What are the implications for other builds?

**Comment by apjanke** [comment]
Reported upstream: unbit/uwsgi#1056.

**Comment by apjanke** [comment]
@alexanderfrey: ` xcode-select --install` isn't sufficient, they're talking about putting specifically the 10.10 Command Line Tools on your 10.11 system.

**Comment by xrmx** [comment]
In the meantime a new stable version is the release you can cherry pick b608eb1772641d525bfde268fe9d6d8d0d5efde7 from uwsgi master.

```
commit b608eb1772641d525bfde268fe9d6d8d0d5efde7
Author: Ragnar Rova <ragnar.rova@gmail.com>
Date:   Wed Jul 15 00:17:46 2015 +0200

    OSX 10.11 supports TCP_FASTOPEN
    
    But does not define SOL_TCP.
    IPPROTO_TCP is the equivalent.

diff --git a/core/socket.c b/core/socket.c
index 8f40043..f75bea9 100644
--- a/core/socket.c
+++ b/core/socket.c
@@ -712,6 +712,11 @@ int bind_to_tcp(char *socket_name, int listen_queue, char *tcp_port) {
 
        if (uwsgi.tcp_fast_open) {
 #ifdef TCP_FASTOPEN
+
+    #ifndef SOL_TCP
+    #define SOL_TCP IPPROTO_TCP
+    #endif
+
                if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uwsgi.tcp_fast_open, sizeof(int)) < 0) {
                        uwsgi_error("TCP_FASTOPEN setsockopt()");
                }
```

**Comment by apjanke** [comment]
Confirmed this fixes it, at least on my 10.11 box.

Since it's fixed in upstream HEAD, just gonna wait until the next release unless folks need this urgently.

**Comment by hughrawlinson** [comment]
I'm still getting this same error on 10.11. Has the fix happened, and is this another issue?

**Comment by DomT4** [comment]
Works fine locally. Should have been fixed by https://github.com/Homebrew/homebrew/commit/85246c03bef2137a1eb00e7f19e9b344123e2706. Are you up-to-date?

**Comment by yoanisgil** [comment]
I had this issue while with 2.0.9/2.01.0/2.0.11 but 2.0.12 fixed it for me (running OS X 10.11).
