### ISSUE TITLE
whereami failed to build on 10.11

### ISSUE THREAD

**Issue by apjanke** [Homebrew/homebrew#44044]
https://gist.github.com/7d7da4f9f9a4ad0d3db3

Swift compilation failure of some sort. May be a Swift version compatibility issue with the update in Xcode 7.

```
[...snip...]
/tmp/whereami20150916-39009-ycsmz1/whereami-1.0/whereami/SwiftCLI/SignatureParser.swift:120:71: error: 'utf16Count' is unavailable: Take the count of a UTF-16 view instead, i.e. str.utf16.count
        return arg.substringWithRange(NSMakeRange(1 * multiplier, key.utf16Count - 2 * multiplier))
                                                                      ^~~~~~~~~~
Foundation.String:224:7: note: 'utf16Count' has been explicitly marked unavailable here
  var utf16Count: Int { get }
      ^

** INSTALL FAILED **
```

**Comment by DomT4** [comment]
It doesn't build on 10.10 either these days. I asked upstream for a new release a fair while ago: https://github.com/victor/whereami/issues/15. It's probably going to keep the rest of the :skull:s company soon.

**Comment by DomT4** [comment]
Closed by https://github.com/Homebrew/homebrew/commit/5fb01ee1a59a9418f9819f3cb09df7ad14b875bb.
