### ISSUE TITLE
Yap failed to build on 10.10

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew#41558]
This is a follow-up to #35936. I don’t know if this is related to #35859.

```
$ brew install yap
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/yap-6.2.2.tar.gz
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/
==> make
      _p_trie_usage in tries.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [tries.dylib] Error 1
make: *** [all] Error 2
```

==> [gist logs](https://gist.github.com/67cf3182037fb9e26088) <==

**Comment by rdp** [comment]
10.10 gcc 5.2.0 I get

$ brew install yap
==> Downloading http://www.dcc.fc.up.pt/~vsc/Yap/yap-6.2.2.tar.gz
######################################################################## 100.0%
==> ./configure --enable-tabling --enable-depth-limit --enable-coroutining --enable-threads --enable-pthread-locking --with-gmp=/usr/local/opt/gmp --with-readline=/usr/local/opt/readlin

==> make
Last 15 lines from /Users/packrd/Library/Logs/Homebrew/yap/02.make:
      _p_trie_to_list in tries.o
  "_trie_traverse_cont", referenced from:
      _p_trie_traverse_cont in tries.o
  "_trie_traverse_first", referenced from:
      _p_trie_traverse_first in tries.o
  "_trie_traverse_init", referenced from:
      _p_trie_traverse_init in tries.o
  "_trie_traverse_next", referenced from:
      _p_trie_traverse_next in tries.o
  "_trie_usage", referenced from:
      _p_trie_usage in tries.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[1]: *** [tries.dylib] Error 1
make: *** [all] Error 2

**Comment by apjanke** [comment]
Same error on 10.9.5 and 10.11.1 for me.

**Comment by apjanke** [comment]
Looks like an incompatibility with our GCC 5? Surprising, since GCC seems to be their main target. Though maybe not, since their last release was Oct-28-2010.

I was able to get `yap` to build on OS X 10.9.5 by uninstalling the Homebrewed `gcc`. Though it did complain about GMP being built under a different compiler. With that in place, it ended up compiling with the system `gcc-4.9`, and the build succeeded.

Adding `fails_with :gcc => "5"` to the formula got it building, even with Homebrew `gcc` installed.

(Adding a simple `fails_with :gcc` to the `yap` formula had no effect; it kept building with `gcc-5`. Shouldn't that work?)

**Comment by mistydemeo** [comment]
> (Adding a simple fails_with :gcc to the yap formula had no effect; it kept building with gcc-5. Shouldn't that work?)

For ~historical reasons~, `:gcc` means Apple's GCC 4.2 and no other GCC. The newer `:gcc => version` syntax came later, and for compatibility we're unable to change the semantics on the older syntax.
