### ISSUE TITLE
geos failed to build on 10.11.3

### ISSUE THREAD

**Issue by nextstopsun** [Homebrew/homebrew#49725]
When running `brew upgrade -v geos` from 3.4.2 to 3.5.0 I get a linker error 
`ld: symbol(s) not found for architecture x86_64` 
Full logs here:
https://gist.github.com/2fe9d850b29cc6bd1ce8

**Comment by tdsmith** [comment]
```
configure:18276: checking for python
configure:18294: found /usr/bin/python
configure:18306: result: /usr/bin/python
...
configure:18431: checking for Python include path
configure:18440: result: /usr//local/Cellar/pypy/4.0.1/libexec/include
```

Well, _that's_ wrong.

**Comment by tdsmith** [comment]
It turns out geos's configure does really inane things to find Python that will blow up on Xcode-only systems with pypy installed:

```bash
        # Check for Python include path
        { $as_echo "$as_me:${as_lineno-$LINENO}: checking for Python include path" >&5
$as_echo_n "checking for Python include path... " >&6; }
        for i in "$base_python_path/include/python$PYTHON_VERSION/" "$base_python_path/include/python/" "$base_python_path/include/" "$base_python_path/" ; do
                python_path=`find $i -type f -name Python.h -print 2> /dev/null | sed "1q"`
                if test -n "$python_path" ; then
                        break
                fi
        done
        python_path=`echo $python_path | sed "s,/Python.h$,,"`
        { $as_echo "$as_me:${as_lineno-$LINENO}: result: $python_path" >&5
$as_echo "$python_path" >&6; }
        if test -z "$python_path" ; then
                as_fn_error $? "cannot find Python include path" "$LINENO" 5
        fi
        PYTHON_CPPFLAGS=-I$python_path
```
